#!/usr/bin/env bash

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 install:"
    echo "        Install Fedora System"
    echo
    echo " e.g: $0 dnf check-update"
    exit "$1"
}

readonly WS_WAYLAND="Wayland"
readonly WS_X11="X11"
readonly WM_KDE="KDE"
readonly WM_GNOME="Gnome"
WINDOW_SYSTEM="$WS_WAYLAND"
WINDOW_MANAGER="$WM_GNOME"

install_berkeley_mono_font() {
    [ ! -d "$(pwd)"/fonts ] && notify-send "$(pwd)/fonts is not a directory" --expire-time=20 && return
    [ ! -f "$(pwd)"/fonts/berkeley-mono-typeface.tar.gz.gpg ] &&
        notify-send "$(pwd)/fonts/berkeley-mono-typeface.tar.gz.gpg does not exists" --expire-time=20 && return
    [ ! -f "$(pwd)"/../scripts/+crypt ] &&
        notify-send "$(pwd)/../scripts/+crypt script does not exists" --expire-time=20 && return
    [ ! -d "$HOME"/Workspace/Software/fonts ] && mkdir -p "$HOME"/Workspace/Software/fonts
    [ -d "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface ] &&
        rm -rf "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface

    # copy and decrypt Berkeley Mono typeface
    cp "$(pwd)"/fonts/berkeley-mono-typeface.tar.gz.gpg "$HOME"/Workspace/Software/fonts
    [ ! -f "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface.tar.gz.gpg ] &&
        notify-send "$HOME/Workspace/Software/fonts/berkeley-mono-typeface.tar.gz.gpg does not exists" \
                    --expire-time=20 && return
    "$(pwd)"/../scripts/+crypt -d "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface.tar.gz.gpg
    [ ! -d "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface ] &&
        notify-send "Decryption failed, $HOME/Workspace/Software/fonts/berkeley-mono-typeface does not exists" \
                    --expire-time=20 && return

    # just in case
    mkdir -p ~/.local/share/fonts

    # remove all fonts from ~/.local/share/fonts that start with "BerkeleyMono"
    rm -rf ~/.local/share/fonts/Berkeley*

    # copy all V1 TTF fonts to ~/.local/share/fonts
    # find "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface/TX-01/ \
    #      -type f -name "*.ttf" -exec cp {} "$HOME"/.local/share/fonts/ \; -print

    # copy all V2 OTF fonts to ~/.local/share/fonts
    find "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface/TX-02/ \
         -type f -name "*.otf" -exec cp {} "$HOME"/.local/share/fonts/ \; -print

    # Build font information caches
    fc-cache -f

    # cleanup
    [ -d "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface ] &&
        rm -rf "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface
}

fedora_install() {
    HEIGHT=25
    WIDTH=100
    CHOICE_HEIGHT=4
    BACKTITLE="Fedora Setup Util"
    TITLE="Please Make a selection"
    MENU="Please Choose one of the following options:"

    # Accept WS and WM for the installer to kick in
    read -rp "$BACKTITLE (WS=$WINDOW_SYSTEM and WM=$WINDOW_MANAGER)? (Y/N): " confirm
    [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || usage 1
    case $WINDOW_SYSTEM in
        "$WS_WAYLAND" | "$WS_X11") ;;
        *)
            echo "Error. Please select one of the supported Window Systems"
            usage 1
            ;;
    esac
    case $WINDOW_MANAGER in
        "$WM_KDE" | "$WM_GNOME") ;;
        *)
            echo "Error. Please select one of the supported Window Managers"
            usage 1
            ;;
    esac

    # Check to see if Dialog is installed, if not install it
    if [ "$(rpm -q dialog 2> /dev/null | grep -c "is not installed")" -eq 1 ]; then
        sudo dnf install -y dialog
    fi

    # Check to see if libnotify is installed, if not install it
    if [ "$(rpm -q libnotify 2> /dev/null | grep -c "is not installed")" -eq 1 ]; then
        sudo dnf install -y libnotify
    fi

    OPTIONS=(
        1 "Setup Defaults - Set some defaults (hostname, folders structure, global settings, etc)"
        2 "Setup RPM Fussion - Update Kernel, RPM Fussion & Firmware (reboot needed)"
        3 "Install NVIDIA - Install NVIDIA Drivers (reboot needed)"
        4 "Install Software - Installs a bunch of my most used software"
        5 "Install Extras - Themes Fonts and Codecs"
        6 "Enable Flatpak - Enables the Flatpak repo and installs packages"
        7 "Setup Secrets and Repos - Setup ssh and gpg from backups and get git repos"
        8 "Install Emacs - Install Emacs"
        9 "Install StyLua - Install StyLua from source"
        10 "Install Keyd - Install Keyd from source"
        11 "Install Gnome Extensions - Install Gnome Extensions"
        12 "Install Xremap - Install Xremap from source"
        13 "Install Harper - The English grammar checker designed to be just right"
        14 "Quit")

    while true; do
        CHOICE=$(dialog --clear \
                        --backtitle "$BACKTITLE" \
                        --title "$TITLE" \
                        --nocancel \
                        --menu "$MENU" \
                        $HEIGHT $WIDTH $CHOICE_HEIGHT \
                        "${OPTIONS[@]}" \
            2>&1 > /dev/tty)

        clear
        case $CHOICE in
            1)
                echo "$CHOICE) Setting Defaults"

                # hostname
                read -r -p "Enter pretty hostname (defaults to 'Julio's Personal Laptop'): " HOSTNAME_PRETTY
                [ -z "$HOSTNAME_PRETTY" ] && HOSTNAME_PRETTY="Julio's Personal Laptop"
                hostnamectl set-hostname --pretty "$HOSTNAME_PRETTY"

                read -r -p "Enter static hostname (defaults to 'fedora-xps-9710'): " HOSTNAME_STATIC
                [ -z "$HOSTNAME_STATIC" ] && HOSTNAME_STATIC="fedora-xps-9710"
                hostnamectl set-hostname --static "$HOSTNAME_STATIC"

                # xdg
                export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
                export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
                export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
                export XDG_LIB_HOME="${XDG_DATA_HOME:-$HOME/.local/lib}"
                export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
                mkdir -p \
                      "${XDG_CACHE_HOME}" \
                      "${XDG_CONFIG_HOME}" \
                      "${XDG_DATA_HOME}" \
                      "${XDG_LIB_HOME}" \
                      "${XDG_STATE_HOME}"

                # Folder structure
                mkdir -p "$HOME/.local/bin"
                mkdir -p "$HOME/Workspace"
                mkdir -p "$HOME/Workspace/Books"
                mkdir -p "$HOME/Workspace/Private/Projects"
                mkdir -p "$HOME/Workspace/Public"
                mkdir -p "$HOME/Workspace/Software"
                mkdir -p "$HOME/Workspace/Stuff"
                mkdir -p "$HOME/Workspace/Work"
                mkdir -p "$HOME/Workspace/Work/Projects"
                mkdir -p "$HOME/Workspace/Work/Software"
                mkdir -p "$HOME/Workspace/Work/Stuff"

                # Gnome Gsettings - dconf-editor
                #  - View current settings - gsettings list-recursively org.gnome.desktop.interface
                #  - Reset to default setting - gsettings reset org.gnome.desktop.interface enable-animations
                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    # Clock Settings
                    gsettings set org.gnome.desktop.interface clock-format '12h'
                    gsettings set org.gnome.desktop.interface clock-show-date true
                    gsettings set org.gnome.desktop.interface clock-show-seconds false
                    gsettings set org.gnome.desktop.interface clock-show-weekday false

                    # No hot corners
                    gsettings set org.gnome.desktop.interface enable-hot-corners false

                    # Emacs please
                    gsettings set org.gnome.desktop.interface gtk-key-theme 'Emacs'

                    # Show battery
                    gsettings set org.gnome.desktop.interface show-battery-percentage true

                    # Enable window buttons
                    gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'

                    # Set new windows centered
                    gsettings set org.gnome.mutter center-new-windows true

                    # Set list-view for Nautilius
                    gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'

                    # Force alt + tab to switch only on current workspace
                    gsettings set org.gnome.shell.app-switcher current-workspace-only true

                    # Allow max volume
                    gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true

                    # Set fractional scaling (only for wayland)
                    gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"

                    # Stop Gnome Software downloading updates
                    # gsettings set org.gnome.software allow-updates false
                    # gsettings set org.gnome.software download-updates false
                    # gsettings set org.gnome.software download-updates-notify false
                fi

                #
                # Grub
                #

                # Grub should load in graphical mode and the resolution should be right
                # sudo cp /etc/default/grub /etc/default/grub.bak
                # sudo sed -i 's/GRUB_TERMINAL_OUTPUT="console"/GRUB_TERMINAL_OUTPUT="gfxterm"/' /etc/default/grub

                # TODO: add nvidia.NVreg_EnableGpuFirmware=0 to the end of GRUB_CMDLINE_LINUX in /etc/default/grub
                # TODO: add nvidia_drm.modeset=1 to the end of GRUB_CMDLINE_LINUX in /etc/default/grub

                # Apply Grub configuration
                # sudo cp /boot/grub2/grub.cfg /boot/grub2/grub.cfg.bak
                # sudo grub2-mkconfig -o /boot/grub2/grub.cfg

                # Setup dnf configs and update
                echo 'max_parallel_downloads=10' | sudo tee -a /etc/dnf/dnf.conf
                sudo dnf upgrade -y --refresh

                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            2)
                echo "$CHOICE) Setting up RPM Fusion and Updating Firmware"

                # update kernel
                sudo dnf install -y gcc kernel-headers kernel-devel

                # Enable RPM Fusion
                sudo dnf install -y \
                     https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm \
                     https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm

                # Terra (https://terra.fyralabs.com/)
                sudo dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release

                # Install some packages and firmware
                sudo dnf install -y rpmfusion-free-release-tainted
                sudo dnf install -y rpmfusion-nonfree-release-tainted
                sudo dnf install -y dnf-plugins-core
                sudo dnf install -y \*-firmware

                # Upgrade everything
                sudo dnf upgrade -y --refresh
                sudo dnf group upgrade core
                sudo dnf4 group update core
                sudo dnf -y update

                # Update system firmware
                sudo fwupdmgr refresh --force
                sudo fwupdmgr get-devices # Lists devices with available updates.
                sudo fwupdmgr get-updates # Fetches list of available updates.
                sudo fwupdmgr update

                read -rp "$CHOICE) Done. Reboot may be needed. Press enter to continue..."
                ;;
            3)
                echo "$CHOICE) Installing NVIDIA Drivers. Disable secure boot in the bios."

                # Using RPM Fusion
                sudo dnf install -y akmod-nvidia
                sudo dnf install -y xorg-x11-drv-nvidia xorg-x11-drv-nvidia-libs
                sudo dnf install -y xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia-cuda-libs
                sudo dnf install -y vdpauinfo libva-vdpau-driver libva-utils
                sudo dnf install -y vulkan vulkan-tools
                sudo dnf install -y xorg-x11-drv-nvidia-power
                systemctl enable nvidia-{suspend,resume,hibernate}

                # Add to Dracut/Plymouth Fix
                echo -e '# Custom Settings\nforce_drivers+=" nvidia nvidia_modeset nvidia_uvm nvidia_drm "' |
                    sudo tee -a /etc/dracut.conf.d/nvidia.conf
                sudo dracut -f

                read -rp "$CHOICE) Done. Reboot may be needed. Press enter to continue..."
                ;;
            4)
                echo "$CHOICE) Installing Software"

                # general
                sudo dnf install -y dnf-plugins-core copr-cli
                sudo dnf group install -y "development-tools" "c-development"
                sudo dnf install -y ripgrep fd-find util-linux-user xprop xwininfo htop btop nvtop
                sudo dnf install -y aspell aspell-en aspell-es autojump atool autoconf automake bat cmake vim
                sudo dnf install -y freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel
                sudo dnf install -y dnsutils dos2unix doxygen msmtp fastfetch
                sudo dnf install -y graphviz htop mercurial ninja-build
                sudo dnf install -y nodejs npm python3 python3-pip
                sudo dnf install -y multimarkdown pandoc poppler poppler-utils poppler-data
                sudo dnf install -y subversion tldr tree w3m wget libtool texinfo
                sudo dnf install -y wordnet shfmt editorconfig glslang ShellCheck parallel
                sudo dnf install -y llvm clang clang-tools-extra libpcap libpcap-devel
                sudo dnf install -y pkg-config openssl openssl-devel flex bison
                sudo dnf install -y tar unar unrar unzip p7zip p7zip-plugins
                sudo dnf install -y ImageMagick ImageMagick-devel ffmpegthumbnailer mediainfo
                sudo dnf install -y sqlite sqlite-devel
                sudo dnf install -y curl libcurl libcurl-devel
                sudo dnf install -y valgrind minicom mc strace tidy
                sudo dnf install -y libatomic libatomic-static
                sudo dnf install -y libunwind libunwind-devel
                sudo dnf install -y gperftools gperftools-libs gperftools-devel
                sudo dnf install -y ffmpegthumbnailer mediainfo
                sudo dnf install -y feh mpv eza
                sudo dnf install -y ncurses-term
                sudo dnf install -y ccache meson
                sudo dnf install -y zlib-devel bzip2 bzip2-devel readline-devel xz xz-devel \
                     libffi-devel findutils tk-devel libyaml-devel
                sudo dnf install -y fortune-mod gnuplot telnet
                sudo dnf install -y libgcrypt libgcrypt-devel

                # Gnome Software
                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    sudo dnf -y install -y gnome-tweaks dconf-editor
                fi

                # Plasma Software
                if [[ "$WINDOW_MANAGER" == "$WM_KDE" ]]; then
                    sudo dnf install -y kdeconnect-kde
                    # sudo dnf install -y yakuake
                    # sudo dnf install -y latte-dock
                    # sudo zypper install -y kazam
                fi

                # Wayland stuff
                if [[ "$WINDOW_SYSTEM" == "$WS_WAYLAND" ]]; then
                    sudo dnf install -y egl-wayland egl-wayland-devel wl-clipboard
                    # sudo dnf install -y ydotool wtype

                    # dependencies needed for https://sr.ht/~geb/dotool/
                    # sudo dnf install -y libxkbcommon-devel scdoc
                fi

                # X11 stuff
                if [[ "$WINDOW_SYSTEM" == "$WS_X11" ]]; then
                    sudo dnf install -y xclip xinput xdotool x11-utils # some X11 tools
                fi

                # tomb
                # Download and extract
                # [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                # pushd "$HOME"/Workspace/Software || {
                #         notify-send "Can't cd into $HOME/Workspace/Software" --expire-time=20
                #         continue
                # }
                # TOMB_RELEASE=Tomb-2.10
                # TOMB_TAR_FILE="$TOMB_RELEASE.tar.gz"
                # curl -LJO https://files.dyne.org/tomb/"$TOMB_TAR_FILE"
                # atool --extract --explain "$TOMB_TAR_FILE" && rm -rf "$TOMB_TAR_FILE"
                # popd || {
                #         notify-send "Can't cd to previous directory" --expire-time=20
                #         continue
                # }
                # # Build and install
                # pushd "$HOME"/Workspace/Software/"$TOMB_RELEASE" || {
                #         notify-send "Can't cd into $HOME/Workspace/Software/$TOMB_RELEASE" --expire-time=20
                #         continue
                # }
                # sudo make install
                # popd || {
                #         notify-send "Can't cd to previous directory" --expire-time=20
                #         continue
                # }

                # Pass (password-store)
                sudo dnf install -y pass

                # Git stuff
                sudo dnf install -y git           # git itself
                # sudo dnf install -y git-email   # support for email based workflow
                # sudo dnf install -y difftastic  # better diffs
                # sudo dnf install -y git-delta   # better diffs
                # terminal git
                # sudo dnf copr enable atim/lazygit -y
                # sudo dnf install -y lazygit

                # tmux: A terminal multiplexer
                sudo dnf install -y tmux

                # alacritty - A fast, cros-platform, OpenGL terminal emulator
                # sudo dnf install -y alacritty

                # foot - the fast, lightweight and minimalistic Wayland terminal emulator.
                [[ "$WINDOW_SYSTEM" == "$WS_WAYLAND" ]] && sudo dnf install -y foot

                # Ghostty
                # sudo dnf copr enable pgdev/ghostty -y
                # sudo dnf install -y ghostty

                # Starship Prompt
                curl -sS https://starship.rs/install.sh | sh

                # gpg
                sudo dnf install -y gpg gnupg2 gnupg-pkcs11-scd pcsc-tools opensc pcsc-lite-ccid
                sudo dnf install -y pinentry-emacs pinentry-tty
                systemctl enable pcscd && systemctl start pcscd

                # yubikey
                sudo dnf install -y yubikey-manager

                # mail
                sudo dnf install -y isync mu maildir-utils gnutls

                # ledger (https://ledger-cli.org/)
                sudo dnf install -y ledger

                # ncdu (text-based disk usage viewer)
                sudo dnf install -y ncdu

                # Borg Backup
                sudo dnf install -y borgbackup

                # Command Line Fuzzy Finder
                # dnf install -y skim
                sudo dnf install -y fzf

                # Emacs (on fedora is up to date but I prefer to compile it myself)
                # sudo dnf install -y emacs
                # sudo dnf install -y libvterm libvterm-devel # necessary for vterm
                # sudo dnf install -y enchant2-devel pkgconf  # necessary for jinx

                # Neovim
                sudo dnf install -y neovim

                # Firewall GUI to manage firewalld
                sudo dnf install -y firewall-config

                # Profile sync daemon
                sudo dnf install -y profile-sync-daemon
                if [ -f /usr/share/psd/contrib/brave ]; then
                    sudo cp /usr/share/psd/contrib/brave /usr/share/psd/browsers
                elif [ -f "$HOME"/Workspace/Public/dotfiles/Common/psd/brave ]; then
                    sudo cp "$HOME"/Workspace/Public/dotfiles/Common/psd/brave /usr/share/psd/browsers
                fi
                systemctl --user enable psd.service && systemctl --user start psd.service

                # Ulauncher
                sudo dnf install -y ulauncher wmctrl

                # Bleachbit: Clean Your System and Free Disk Space
                # sudo dnf install -y bleachbit

                # Go
                sudo dnf install -y go

                # Mullvad VPN (Using Network Manager)
                sudo dnf config-manager addrepo --from-repofile=https://repository.mullvad.net/rpm/stable/mullvad.repo
                sudo dnf install -y mullvad-vpn

                # grammar linter (python)
                # sudo dnf install -y proselint

                # ebook reader/converver
                sudo dnf install -y calibre

                # non dnf software
                pip install cmake-language-server
                pip install pyright
                sudo npm install --global npm@latest
                sudo npm install --global prettier
                sudo npm install --global js-beautify
                sudo npm install --global typescript-language-server typescript
                sudo npm install --global dockerfile-language-server-nodejs
                sudo npm install --global bash-language-server
                sudo npm install --global @devcontainers/cli

                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            5)
                echo "$CHOICE) Installing Extras"

                #
                # Multimedia
                #

                # Old...
                # sudo dnf group upgrade -y sound-and-video
                # sudo dnf install -y libdvdcss
                # sudo dnf install -y gstreamer1-plugins-{bad-\*,good-\*,ugly-\*,base} \
                    #     gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel ffmpeg gstreamer-ffmpeg
                # sudo dnf install -y lame\* --exclude=lame-devel
                # sudo dnf config-manager --set-enabled fedora-cisco-openh264
                # sudo dnf install -y gstreamer1-plugin-openh264 mozilla-openh264
                # sudo dnf group upgrade -y --with-optional Multimedia

                # Install additional codecs
                sudo dnf -y group install multimedia && \
                    sudo dnf -y group upgrade multimedia
                sudo dnf -y group install sound-and-video && \
                    sudo dnf -y group upgrade sound-and-video
                sudo dnf swap 'ffmpeg-free' 'ffmpeg' --allowerasing # Switch to full FFMPEG.
                sudo dnf upgrade @multimedia --setopt="install_weak_deps=False" \
                     --exclude=PackageKit-gstreamer-plugin # Installs gstreamer components.
                                                           # Required if you use Gnome Videos and other dependent applications.
                # Install Hardware Accelerated Codec
                sudo dnf install ffmpeg-libs libva libva-utils
                if test "$(cat /proc/cpuinfo | grep vendor | uniq | grep -iFc "intel")"; then
                    echo "$CHOICE) Installing Hardware Accelerated Codecs for Intel Architecture"
                    sudo dnf swap libva-intel-media-driver intel-media-driver --allowerasing
                    sudo dnf install libva-intel-driver
                elif test "$(cat /proc/cpuinfo | grep vendor | uniq | grep -iFc "amd")"; then
                    echo "$CHOICE) Installing Hardware Accelerated Codecs for AMD Architecture"
                    sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld
                    sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld
                    sudo dnf swap mesa-va-drivers.i686 mesa-va-drivers-freeworld.i686
                    sudo dnf swap mesa-vdpau-drivers.i686 mesa-vdpau-drivers-freeworld.i686
                else
                    echo "$CHOICE) Unknown Architecture. Not Installing Hardware Accelerated Codecs"
                fi

                # OpenH264 for Firefox (Needs to be enabled on Firefox)
                sudo dnf install -y openh264 gstreamer1-plugin-openh264 mozilla-openh264
                sudo dnf config-manager setopt fedora-cisco-openh264.enabled=1

                # Hardware codecs with NVIDIA
                sudo dnf install -y nvidia-vaapi-driver --allowerasing

                # Play a DVD
                sudo dnf install -y rpmfusion-free-release-tainted && sudo dnf install -y libdvdcss

                # Various firmwares
                sudo dnf install -y rpmfusion-nonfree-release-tainted
                sudo dnf --repo=rpmfusion-nonfree-tainted install -y "*-firmware"

                #
                # Brave Browser
                #

                # sudo dnf install dnf-plugins-core
                # sudo dnf config-manager addrepo --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
                # sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
                # sudo dnf install brave-browser

                #
                # Firefox
                #
                # make the start page the default firefox start page
                sudo rm -f /usr/lib64/firefox/browser/defaults/preferences/firefox-redhat-default-prefs.js

                #
                # Wireguard
                #
                sudo dnf install -y wireguard-tools

                #
                # OpenVPN
                #
                sudo dnf install openvpn

                #
                # Docker (using podman)
                #
                #
                # Install and Enable Docker (not working on fedora-38)
                # sudo dnf install -y dnf-plugins-core
                # sudo dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
                # sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
                # sudo systemctl enable docker && sudo systemctl start docker
                #
                # add user
                # sudo usermod -G docker -a "$USER"
                # sudo systemctl restart docker

                #
                # Podman
                #

                sudo dnf install -y podman podman-compose

                #
                # Latex
                #

                sudo dnf install -y texlive-scheme-full

                #
                # Steam extras
                #

                sudo dnf install -y steam-devices

                #
                # Fonts
                #

                sudo dnf install -y libreoffice-opensymbol-fonts
                sudo dnf install -y adobe-source-code-pro-fonts
                sudo dnf install -y jetbrains-mono-fonts-all
                sudo dnf install -y ibm-plex-mono-fonts ibm-plex-sans-fonts ibm-plex-serif-fonts
                sudo dnf install -y rsms-inter-fonts rsms-inter-vf-fonts
                install_berkeley_mono_font

                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    gsettings set org.gnome.desktop.interface font-hinting 'full'
                    gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
                    gsettings set org.gnome.desktop.interface font-name 'Inter Variable 11'
                    gsettings set org.gnome.desktop.interface document-font-name 'Inter 11'
                    gsettings set org.gnome.desktop.interface monospace-font-name 'Berkeley Mono 11'
                    # gsettings set org.gnome.desktop.interface text-scaling-factor 1.25 # using fractional scaling instead!!
                fi

                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            6)
                echo "$CHOICE) Enabling Flatpak"

                sudo dnf install -y flatpak
                flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
                flatpak update
                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    flatpak install --user -y flathub org.gnome.TextEditor
                    flatpak install --user -y flathub org.gnome.Firmware
                    flatpak install --user -y flathub com.mattjakeman.ExtensionManager
                fi
                flatpak install --user -y flathub com.discordapp.Discord
                flatpak install --user -y flathub com.dropbox.Client
                flatpak install --user -y flathub com.slack.Slack
                flatpak install --user -y flathub org.videolan.VLC
                flatpak install --user -y flathub org.wireshark.Wireshark
                flatpak install --user -y flathub com.github.tchx84.Flatseal
                flatpak install --user -y flathub com.github.johnfactotum.Foliate
                flatpak install --user -y flathub org.gimp.GIMP
                flatpak install --user -y flathub com.transmissionbt.Transmission
                flatpak install --user -y flathub org.telegram.desktop
                flatpak install --user -y flathub io.podman_desktop.PodmanDesktop
                flatpak install --user -y flathub com.valvesoftware.Steam
                flatpak install --user -y org.freedesktop.Platform.VulkanLayer.MangoHud # this is needed for steam!
                # flatpak install --user -y flathub org.keepassxc.KeePassXC
                # flatpak install --user -y flathub com.borgbase.Vorta
                # flatpak install --user -y flathub io.github.Hexchat
                # flatpak install --user -y flathub engineer.atlas.Nyxt
                # flatpak install --user -y flathub org.mozilla.firefox
                # flatpak install --user -y flathub org.gnucash.GnuCash
                # flatpak install --user -y flathub im.riot.Riot
                # flatpak install --user -y flathub com.obsproject.Studio
                # flatpak install --user -y flathub com.brave.Browser
                # flatpak install --user -y flathub org.shotcut.Shotcut
                # flatpak install --user -y flathub dev.geopjr.Tuba
                # flatpak install --user -y flathub io.github.mimbrero.WhatsAppDesktop
                # flatpak install --user -y flathub org.signal.Signal
                # flatpak install --user -y flathub com.microsoft.Edge
                # flatpak install --user -y flathub com.visualstudio.code
                # flatpak install --user -y flathub com.github.GradienceTeam.Gradience

                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            7)
                echo "$CHOICE) Setting up secrets and repos"
                read -r -p "Enter keys backup directory: " KEYS_DIR
                KEYS_DIR=${KEYS_DIR%/}
                [ ! -d "$KEYS_DIR" ] && notify-send "$KEYS_DIR is not a directory" --expire-time=20 && continue
                [ ! -f "$(pwd)/../scripts/+crypt" ] && notify-send "$(pwd)/../scripts/+crypt script does not exists" \
                                                                   --expire-time=20 && continue
                [ ! -f "$KEYS_DIR/ssh.tar.gz.gpg" ] && notify-send "$KEYS_DIR/ssh.tar.gz.gpg does not exists" \
                                                                   --expire-time=20 && continue
                [ ! -f "$KEYS_DIR/gpg.tar.gz.gpg" ] && notify-send "$KEYS_DIR/gpg.tar.gz.gpg does not exists" \
                                                                   --expire-time=20 && continue

                echo ">> Setting up ssh keys from $KEYS_DIR/ssh.tar.gz.gpg"
                "$(pwd)/../scripts/+crypt" -d "$KEYS_DIR/ssh.tar.gz.gpg"
                [ ! -d "$KEYS_DIR"/.ssh ] && notify-send "Decryption failed, $KEYS_DIR/ssh does not exists" \
                                                        --expire-time=20 && continue
                mkdir -p ~/.ssh && rm -rf ~/.ssh/*
                cp "$KEYS_DIR"/.ssh/id_* ~/.ssh
                cp "$KEYS_DIR"/.ssh/config ~/.ssh
                chmod 700 ~/.ssh
                chmod 644 ~/.ssh/config
                chmod 600 ~/.ssh/id_*
                chmod 644 ~/.ssh/id_*.pub
                rm -rf "$KEYS_DIR"/.ssh

                echo ">> Setting up gpg keys from $KEYS_DIR/gpg.tar.gz.gpg"
                "$(pwd)/../scripts/+crypt" -d "$KEYS_DIR/gpg.tar.gz.gpg"
                [ ! -d "$KEYS_DIR"/gpg ] && notify-send "Decryption failed, $KEYS_DIR/gpg does not exists" \
                                                        --expire-time=20 && continue
                mkdir -p ~/.gnupg && rm -rf ~/.gnupg/*
                cp "$KEYS_DIR"/gpg/config/*.conf ~/.gnupg
                gpg --import "$KEYS_DIR"/gpg/new_keys/0xB3F739419D91C7F3-2022-09-28.pub.asc
                rm -rf "$KEYS_DIR"/gpg

                echo "Editing gpg key 0xB3F..., you should 'trust' ultimately (Option 5) and 'quit'"
                gpg --edit-key 0xB3F739419D91C7F3

                # Remove keys
                rm -rf "$KEYS_DIR"

                # With the new keys we can go ahead and download some repos
                [ ! -d "$HOME/.password-store" ] &&
                    git clone git@github.com:jvillasante/pass.git "$HOME"/.password-store
                [ ! -d "$HOME"/Workspace/Public/dotfiles ] &&
                    git clone git@github.com:jvillasante/dotfiles.git "$HOME"/Workspace/Public/dotfiles
                [ ! -d "$HOME"/Workspace/Public/resume ] &&
                    git clone git@github.com:jvillasante/resume.git "$HOME"/Workspace/Public/resume

                # Set dotfiles
                if [ -f "$HOME"/Workspace/Public/dotfiles/make.sh ]; then
                    [ -f "$HOME"/.bashrc ] && mv "$HOME"/.bashrc "$HOME"/.bashrc.bak
                    [ -f "$HOME"/.bash_profile ] && mv "$HOME"/.bash_profile "$HOME"/.bash_profile.bak
                    [ -d "$HOME"/.config/psd ] && rm -rf "$HOME"/.config/psd
                    "$HOME"/Workspace/Public/dotfiles/make.sh

                    # Udev rules for ZSA Voyager
                    sudo cp -f "$HOME"/Workspace/Public/dotfiles/Common/udev/50-zsa.rules \
                         /etc/udev/rules.d/50-zsa.rules
                fi

                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            8)
                echo "$CHOICE) Installing emacs-lsp-booster & Emacs"

                #
                # First install emacs-lsp-booster to speed up lsp in emacs
                #

                # Is it already installed?
                hash emacs-lsp-booster 2> /dev/null && notify-send "emacs-lsp-booster is already installed" --expire-time=20 && continue

                # Install
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                [ ! -d "$HOME"/Workspace/Software/emacs-lsp-booster ] && mkdir -p "$HOME"/Workspace/Software/emacs-lsp-booster

                pushd "$HOME"/Workspace/Software/emacs-lsp-booster || {
                        notify-send "Can't cd into $HOME/Workspace/Software/emacs-lsp-booster" --expire-time=20
                        continue
                }

                EMACS_LSP_BOOSTER_VERSION=v0.2.1
                EMACS_LSP_BOOSTER_RELEASE=emacs-lsp-booster_"$EMACS_LSP_BOOSTER_VERSION"_x86_64-unknown-linux-musl.zip
                curl -LJO https://github.com/blahgeek/emacs-lsp-booster/releases/download/"$EMACS_LSP_BOOSTER_VERSION"/"$EMACS_LSP_BOOSTER_RELEASE"
                atool --extract --explain "$EMACS_LSP_BOOSTER_RELEASE"
                sudo cp -f emacs-lsp-booster /usr/local/bin/

                popd || {
                        notify-send "Can't cd to previous directory" --expire-time=20
                        continue
                }

                #
                # We are now ready to install emacs
                #

                # Is it already installed?
                hash emacs 2> /dev/null && notify-send "Emacs is already installed" --expire-time=20 && continue

                # Install dependencies
                sudo dnf group install "development-tools"
                sudo dnf -y builddep emacs

                # images packages install
                sudo dnf install -y Xaw3d Xaw3d-devel libpng libpng-devel zlib libjpeg-turbo libjpeg-devel \
                     libtiff libtiff-devel giflib giflib-devel librsvg2 librsvg2-devel libwebp libwebp-devel \
                     ImageMagick ImageMagick-devel

                # emacs packages install
                sudo dnf install -y autoconf gnutls-devel gmp-devel gtk3-devel gtk4-devel jansson-devel \
                     libgccjit libgccjit-devel libmpc-devel libvterm-devel mpfr-devel ncurses-devel texinfo

                # tree-sitter packages
                sudo dnf install -y libtree-sitter libtree-sitter-devel tree-sitter-cli gcc-c++

                # enchant package (jinx)
                sudo dnf install -y enchant2-devel pkgconf # necessary for jinx

                # Prepare git repo
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                if [ ! -d "$HOME"/Workspace/Software/emacs ]; then
                    git clone git://git.sv.gnu.org/emacs.git "$HOME"/Workspace/Software/emacs
                    pushd "$HOME"/Workspace/Software/emacs || {
                        notify-send "Can't cd into $HOME/Workspace/Software/emacs" --expire-time=20
                        continue
                    }
                else
                    pushd "$HOME"/Workspace/Software/emacs || {
                        notify-send "Can't cd into $HOME/Workspace/Software/emacs" --expire-time=20
                        continue
                    }

                    sudo make uninstall
                    make clean && make distclean
                    git reset --hard HEAD
                    sudo git clean -dfx
                fi

                # Setup git branch
                local BRANCH
                BRANCH=$(git branch --show-current)
                [[ "$BRANCH" != emacs-30 ]] && git checkout emacs-30
                git fetch && git pull

                # Install
                ./autogen.sh
                ./configure \
                    --prefix=/usr/local \
                    --with-modules \
                    --with-pgtk \
                    --with-x-toolkit=no \
                    --without-compress-install \
                    --with-native-compilation=aot \
                    --with-tree-sitter \
                    --without-mailutils \
                    --with-selinux \
                    --with-xinput2 \
                    --with-dbus \
                    --disable-gc-mark-trace \
                    CFLAGS="-O3 -fno-math-errno -funsafe-math-optimizations -fno-finite-math-only -fno-trapping-math \
                            -freciprocal-math -fno-rounding-math -fno-signaling-nans -fassociative-math \
                            -fno-signed-zeros -frename-registers -funroll-loops -mtune=native -march=native \
                            -fomit-frame-pointer -fallow-store-data-races -fno-semantic-interposition \
                            -floop-parallelize-all -ftree-parallelize-loops=4"
                make -j"$(nproc --ignore=2)"
                sudo make install

                popd || notify-send "Can't cd to previous directory" --expire-time=20

                # Update packages
                read -rp "Emacs has been installed, do you want to update packages now? (Y/N): " confirm
                if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
                    local DOTFILES_DIR
                    DOTFILES_DIR="$HOME"/Workspace/Public/dotfiles/

                    [[ ! -d "$DOTFILES_DIR"/Common/emacs/emacs.d ]] &&
                        echo "Emacs personal configuration not found, exiting..." && usage 1
                    [[ -d "$DOTFILES_DIR"/Common/emacs/emacs.d/var/eln-cache ]] &&
                        rm -rf "$DOTFILES_DIR"/Common/emacs/emacs.d/var/eln-cache
                    [[ -d "$DOTFILES_DIR"/Common/emacs/emacs.d/var/elpa ]] &&
                        rm -rf "$DOTFILES_DIR"/Common/emacs/emacs.d/var/elpa
                    [[ -d "$DOTFILES_DIR"/Common/emacs/emacs.d/var/tree-sitter ]] &&
                        rm -rf "$DOTFILES_DIR"/Common/emacs/emacs.d/var/tree-sitter
                    /usr/local/bin/emacs --init-directory="$DOTFILES_DIR"/Common/emacs/emacs.d
                fi

                read -rp "Emacs packages updated, do you want to start the systemd service now? (Y/N): " confirm
                if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]; then
                    systemctl --user daemon-reload
                    sleep 1 && systemctl --user enable emacs.service
                    sleep 1 && systemctl --user start emacs.service
                    sleep 1 && systemctl --user status emacs.service
                fi

                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            9)
                echo "$CHOICE Installing StyLua"

                 # Is it already installed?
                hash stylua 2> /dev/null && notify-send "StyLua is already installed" --expire-time=20 && continue

                # Install
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                [ ! -d "$HOME"/Workspace/Software/stylua ] && mkdir -p "$HOME"/Workspace/Software/stylua

                pushd "$HOME"/Workspace/Software/stylua || {
                        notify-send "Can't cd into $HOME/Workspace/Software/stylua" --expire-time=20
                        continue
                }

                STYLUA_VERSION=v2.1.0
                STYLUA_RELEASE=stylua-linux-x86_64.zip
                curl -LJO https://github.com/JohnnyMorganz/StyLua/releases/download/"$STYLUA_VERSION"/"$STYLUA_RELEASE"
                atool --extract --explain "$STYLUA_RELEASE"
                sudo cp -f stylua /usr/local/bin/

                popd || {
                        notify-send "Can't cd to previous directory" --expire-time=20
                        continue
                }

                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            10)
                echo "$CHOICE) Installing Keyd"

                # Is it already installed?
                hash keyd 2> /dev/null && notify-send "Keyd is already installed" --expire-time=20 && continue

                # Prepare git repo
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                if [ ! -d "$HOME"/Workspace/Software/keyd ]; then
                    git clone git@github.com:rvaiya/keyd.git "$HOME"/Workspace/Software/keyd
                    pushd "$HOME"/Workspace/Software/keyd || {
                        notify-send "Can't cd into $HOME/Workspace/Software/keyd" --expire-time=20
                        continue
                    }
                else
                    pushd "$HOME"/Workspace/Software/keyd || {
                        notify-send "Can't cd into $HOME/Workspace/Software/keyd" --expire-time=20
                        continue
                    }

                    sudo make uninstall
                    make clean && make distclean
                    git reset --hard HEAD
                    sudo git clean -dfx
                    git pull
                fi

                # Install
                make -j"$(nproc --ignore=2)"
                sudo make install

                # Copy Configuration
                sudo cp "$HOME"/Workspace/Public/dotfiles/Common/keyd/default.conf /etc/keyd/default.conf

                # Add yourself to the keyd group
                sudo usermod -aG keyd -a "$USER"

                # Enable the daemon
                sudo systemctl daemon-reload
                sudo systemctl enable keyd && sudo systemctl start keyd
                sudo keyd reload

                popd || notify-send "Can't cd to previous directory" --expire-time=20
                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            11)
                echo "11) Installing Gnome Extensions"

                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                    [ ! -d "$HOME"/Workspace/Software/unite ] && mkdir -p "$HOME"/Workspace/Software/unite

                    pushd "$HOME"/Workspace/Software/unite || {
                        notify-send "Can't cd into $HOME/Workspace/Software/unite" --expire-time=20
                        continue
                    }

                    UNITE_VERSION=v82
                    curl -LJO https://github.com/hardpixel/unite-shell/releases/download/"$UNITE_VERSION"/unite-"$UNITE_VERSION".zip
                    gnome-extensions install --force unite-"$UNITE_VERSION".zip

                    popd || notify-send "Can't cd to previous directory" --expire-time=20
                fi

                read -rp "11) Gnome extensions installed."
                ;;
            12)
                echo "12) Installing Xremap"

                [[ "$WINDOW_SYSTEM" == "$WS_X11" ]] && sudo dnf install -y libx11-devel

                # Is it already installed?
                hash xremap 2> /dev/null && notify-send "Xremap is already installed" --expire-time=20 && continue

                # Install
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                [ ! -d "$HOME"/Workspace/Software/xremap ] && mkdir -p "$HOME"/Workspace/Software/xremap

                pushd "$HOME"/Workspace/Software/xremap || {
                        notify-send "Can't cd into $HOME/Workspace/Software/xremap" --expire-time=20
                        continue
                }

                XREMAP_VERSION=v0.10.11
                XREMAP_RELEASE=xremap-linux-x86_64-kde.zip
                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    XREMAP_RELEASE=xremap-linux-x86_64-gnome.zip
                fi

                curl -LJO https://github.com/k0kubun/xremap/releases/download/"$XREMAP_VERSION"/"$XREMAP_RELEASE"
                atool --extract --explain "$XREMAP_RELEASE"
                sudo cp -f xremap /usr/local/bin/

                popd || {
                        notify-send "Can't cd to previous directory" --expire-time=20
                        continue
                }

                # First create a new group to which we allow access to the input stuff; add this group to your user:
                sudo gpasswd -a "$USER" input

                # Second Create new udev rule granting access:
                sudo cp -f "$HOME"/Workspace/Public/dotfiles/Common/udev/70-xremap.rules \
                     /etc/udev/rules.d/70-xremap.rules

                # Enable the daemon
                [ ! -d "$HOME"/.config/systemd/user ] && mkdir -p "$HOME"/.config/systemd/user
                [ -L "$HOME/.config/systemd/user/xremap.service" ] &&
                    unlink "$HOME/.config/systemd/user/xremap.service"
                ln -s "$HOME/Workspace/Public/dotfiles/Common/systemd/user/xremap.service" \
                    "$HOME/.config/systemd/user"
                systemctl --user daemon-reload
                systemctl --user enable xremap.service && systemctl --user start xremap.service

                read -rp "12) Xremap installed. Reboot for udev rules to take effect.
                              On Gnome, install the extension at https://extensions.gnome.org/extension/5060/xremap/.
                              Press enter to continue..."
                ;;
            13)
                echo "13) Installing Harper"

                # Is it already installed?
                hash harper-cli 2> /dev/null && notify-send "Harper is already installed" --expire-time=20 && continue
                hash harper-ls 2> /dev/null && notify-send "Harper is already installed" --expire-time=20 && continue

                # Install
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                [ ! -d "$HOME"/Workspace/Software/harper ] && mkdir -p "$HOME"/Workspace/Software/harper

                pushd "$HOME"/Workspace/Software/harper || {
                        notify-send "Can't cd into $HOME/Workspace/Software/harper" --expire-time=20
                        continue
                }

                HARPER_VERSION=v0.27.0
                HARPER_CLI_RELEASE=harper-cli-x86_64-unknown-linux-gnu.tar.gz
                HARPER_LS_RELEASE=harper-ls-x86_64-unknown-linux-gnu.tar.gz

                curl -LJO https://github.com/Automattic/harper/releases/download/"$HARPER_VERSION"/"$HARPER_CLI_RELEASE"
                atool --extract --explain "$HARPER_CLI_RELEASE"
                sudo cp -f harper-cli /usr/local/bin/

                curl -LJO https://github.com/Automattic/harper/releases/download/"$HARPER_VERSION"/"$HARPER_LS_RELEASE"
                atool --extract --explain "$HARPER_LS_RELEASE"
                sudo cp -f harper-ls /usr/local/bin/

                popd || {
                        notify-send "Can't cd to previous directory" --expire-time=20
                        continue
                }

                read -rp "13) Harper installed. Press enter to continue..."
                ;;
            14)
                exit 0
                ;;
        esac
    done
}

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

if [ ! -f /etc/fedora-release ]; then
    echo "Error: Fedora is not running on this system, exiting..."
    exit 1
fi

if ! hash dnf 2> /dev/null; then
    echo "Error: dnf not installed on this system, exiting..."
    exit 1
fi

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    install)
        [ "$nargs" -eq 1 ] || usage 1
        fedora_install "$@"
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
