#!/usr/bin/env bash

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 install:"
    echo "        Install OpenSuse System"
    echo
    echo " e.g: $0 zipper update"
    exit "$1"
}

readonly WS_WAYLAND="Wayland"
readonly WS_X11="X11"
readonly WM_KDE="KDE"
readonly WM_GNOME="Gnome"
WINDOW_SYSTEM="$WS_WAYLAND"
WINDOW_MANAGER="$WM_KDE"

install_berkeley_mono_font() {
    [ ! -d "$(pwd)"/fonts ] && notify-send "$(pwd)/fonts is not a directory" --expire-time=20 && return
    [ ! -f "$(pwd)"/fonts/berkeley-mono-typeface.tar.gz.gpg ] && notify-send "$(pwd)/fonts/berkeley-mono-typeface.tar.gz.gpg does not exists" --expire-time=20 && return
    [ ! -f "$(pwd)"/../scripts/+crypt ] && notify-send "$(pwd)/../scripts/+crypt script does not exists" --expire-time=20 && return
    [ ! -d "$HOME"/Workspace/Software/fonts ] && mkdir -p "$HOME"/Workspace/Software/fonts
    [ -d "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface ] && rm -rf "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface

    # copy and decrypt Berkeley Mono typeface
    cp "$(pwd)"/fonts/berkeley-mono-typeface.tar.gz.gpg "$HOME"/Workspace/Software/fonts
    [ ! -f "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface.tar.gz.gpg ] && notify-send "$HOME/Workspace/Software/fonts/berkeley-mono-typeface.tar.gz.gpg does not exists" --expire-time=20 && return
    "$(pwd)"/../scripts/+crypt -d "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface.tar.gz.gpg
    [ ! -d "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface ] && notify-send "Decryption failed, $HOME/Workspace/Software/fonts/berkeley-mono-typeface directory does not exists" --expire-time=20 && return

    # just in case
    mkdir -p ~/.local/share/fonts

    # remove all fonts from ~/.local/share/fonts that start with "BerkeleyMono"
    rm -rf ~/.local/share/fonts/BerkeleyMono*

    # copy all ttf fonts to ~/.local/share/fonts
    find "$HOME"/Workspace/Software/fonts/berkeley-mono-typeface -type f -name "*.ttf" -exec cp {} "$HOME"/.local/share/fonts/ \; -print

    # Build font information caches
    fc-cache -f
}

install_iosevka_comfy_font() {
    # Prepare git repo
    [ ! -d "$HOME"/Workspace/Software/fonts ] && mkdir -p "$HOME"/Workspace/Software/fonts
    if [ ! -d "$HOME"/Workspace/Software/fonts/iosevka-comfy ]; then
        git clone --depth 1 https://git.sr.ht/~protesilaos/iosevka-comfy "$HOME"/Workspace/Software/fonts/iosevka-comfy
    else
        git --git-dir="$HOME"/Workspace/Software/fonts/iosevka-comfy/.git --work-tree="$HOME"/Workspace/Software/fonts/iosevka-comfy reset --hard HEAD
        git --git-dir="$HOME"/Workspace/Software/fonts/iosevka-comfy/.git --work-tree="$HOME"/Workspace/Software/fonts/iosevka-comfy pull
    fi

    # just in case
    mkdir -p ~/.local/share/fonts

    # remove all fonts from ~/.local/share/fonts that start with "iosevka-comfy"
    rm -rf ~/.local/share/fonts/iosevka-comfy*

    # copy all otf/ttf fonts to ~/.local/share/fonts
    find "$HOME"/Workspace/Software/fonts/iosevka-comfy/ -type f \( -name "*.ttf" -o -name "*.otf" \) -exec cp {} "$HOME"/.local/share/fonts/ \; -print

    # Build font information caches
    fc-cache -f
}

install_monaspace_font() {
    # Prepare git repo
    [ ! -d "$HOME"/Workspace/Software/fonts ] && mkdir -p "$HOME"/Workspace/Software/fonts
    if [ ! -d "$HOME"/Workspace/Software/fonts/monaspace ]; then
        git clone git@github.com:githubnext/monaspace.git "$HOME"/Workspace/Software/fonts/monaspace
    else
        git --git-dir="$HOME"/Workspace/Software/fonts/monaspace/.git --work-tree="$HOME"/Workspace/Software/fonts/monaspace reset --hard HEAD
        git --git-dir="$HOME"/Workspace/Software/fonts/monaspace/.git --work-tree="$HOME"/Workspace/Software/fonts/monaspace pull
    fi

    # just in case
    mkdir -p ~/.local/share/fonts

    # remove all fonts from ~/.local/share/fonts that start with "monaspace"
    rm -rf ~/.local/share/fonts/Monaspace*

    # copy all otf/ttf fonts to ~/.local/share/fonts
    find "$HOME"/Workspace/Software/fonts/monaspace/ -type f \( -name "*.ttf" -o -name "*.otf" \) -exec cp {} "$HOME"/.local/share/fonts/ \; -print

    # Build font information caches
    fc-cache -f
}

suse_install() {
    HEIGHT=25
    WIDTH=100
    CHOICE_HEIGHT=4
    BACKTITLE="OpenSuse Setup Util"
    TITLE="Please Make a selection"
    MENU="Please Choose one of the following options:"

    # Accept WS and WM for the installer to kick in
    read -rp "$BACKTITLE (WS=$WINDOW_SYSTEM and WM=$WINDOW_MANAGER)? (Y/N): " confirm
    [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || usage 1
    case $WINDOW_SYSTEM in
        "$WS_WAYLAND" | "$WS_X11") ;;
        *)
            echo "Error. Please select one of the supported Window Systems"
            usage 1
            ;;
    esac
    case $WINDOW_MANAGER in
        "$WM_KDE" | "$WM_GNOME") ;;
        *)
            echo "Error. Please select one of the supported Window Managers"
            usage 1
            ;;
    esac

    # Check to see if Dialog is installed, if not install it
    hash dialog 2> /dev/null || sudo zypper install -y dialog
    hash notify-send 2> /dev/null || sudo zypper install -y libnotify

    OPTIONS=(
        1 "Do a full system upgrade - Do a full system upgrade (reboot if needed)"
        2 "Setup Packman - Set up packman repository and upgrade (reboot if needed)"
        3 "Firmware Update - Update Firmware (reboot if needed)"
        4 "Setup NVIDIA - Setup and install NVIDIA drivers (reboot if needed)"
        5 "Setup Defaults - Set some defaults (hostname, folders structure, gsettings, etc)"
        6 "Install Software Needed - Post install setup (zram, etc)"
        7 "Install Software General - Installs a bunch of my most used software"
        8 "Install Software Extras - Themes Fonts and Codecs"
        9 "Enable Flatpak - Enables the Flatpak repo and installs packages"
        10 "Setup Secrets and Repos - Setup ssh and gpg from backups and get git repos"
        11 "Install Emacs - Install Emacs"
        12 "Install Keyd - Install Keyd from source (using xremap at the moment, here for documentation only)"
        13 "Install Xkeysnail - Install Xkeysnail from source (using xremap at the moment, here for documentation only)"
        14 "Install Xremap - Install Xremap"
        15 "Quit")

    while true; do
        CHOICE=$(dialog --clear \
            --backtitle "$BACKTITLE" \
            --title "$TITLE" \
            --nocancel \
            --menu "$MENU" \
            $HEIGHT $WIDTH $CHOICE_HEIGHT \
            "${OPTIONS[@]}" \
            2>&1 > /dev/tty)

        clear
        case $CHOICE in
            1)
                echo "$CHOICE) Full System Upgrade"
                sudo zypper ref && sudo zypper dup

                read -rp "$CHOICE) Done (May need to reboot). Press enter to continue..."
                ;;
            2)
                echo "$CHOICE) Setup Packman Repository"
                sudo zypper ar -cfp 90 https://ftp.fau.de/packman/suse/openSUSE_Tumbleweed/ packman
                sudo zypper dup --from packman --allow-vendor-change

                read -rp "$CHOICE) Done (May need to reboot). Press enter to continue..."
                ;;
            3)
                echo "$CHOICE) Firmware Update"
                sudo fwupdmgr get-devices
                sudo fwupdmgr refresh --force
                sudo fwupdmgr get-updates
                sudo fwupdmgr update

                read -rp "$CHOICE) Done (May need to reboot). Press enter to continue..."
                ;;
            4)
                echo "$CHOICE) Setup NVIDIA"
                sudo zypper addrepo -f https://download.nvidia.com/opensuse/tumbleweed nvidia
                sudo zypper install-new-recommends --repo nvidia

                read -rp "$CHOICE) Done (May need to reboot). Press enter to continue..."
                ;;
            5)
                echo "$CHOICE) Setting Defaults"

                # hostname
                read -r -p "Enter pretty hostname (defaults to 'Julio's Personal Laptop'): " HOSTNAME_PRETTY
                [ -z "$HOSTNAME_PRETTY" ] && HOSTNAME_PRETTY="Julio's Personal Laptop"
                hostnamectl set-hostname --pretty "$HOSTNAME_PRETTY"

                read -r -p "Enter static hostname (defaults to 'suse-xps-9710'): " HOSTNAME_STATIC
                [ -z "$HOSTNAME_STATIC" ] && HOSTNAME_STATIC="suse-xps-9710"
                hostnamectl set-hostname --static "$HOSTNAME_STATIC"

                # xdg
                export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
                export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
                export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
                export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
                export XDG_LIB_HOME="${XDG_DATA_HOME:-$HOME/.local/lib}"
                mkdir -p \
                      "${XDG_CONFIG_HOME}" \
                      "${XDG_CACHE_HOME}" \
                      "${XDG_DATA_HOME}" \
                      "${XDG_STATE_HOME}" \
                      "${XDG_LIB_HOME}"

                # Folder structure
                mkdir -p "$HOME/.local/bin"
                mkdir -p "$HOME/Workspace"
                mkdir -p "$HOME/Workspace/Books"
                mkdir -p "$HOME/Workspace/Private/Projects"
                mkdir -p "$HOME/Workspace/Public"
                mkdir -p "$HOME/Workspace/Software"
                mkdir -p "$HOME/Workspace/Stuff"
                mkdir -p "$HOME/Workspace/Work"
                mkdir -p "$HOME/Workspace/Work/Projects"
                mkdir -p "$HOME/Workspace/Work/Software"
                mkdir -p "$HOME/Workspace/Work/Stuff"

                # Gnome Gsettings - dconf-editor
                #  - View current settings - gsettings list-recursively org.gnome.desktop.interface
                #  - Reset to default setting - gsettings reset org.gnome.desktop.interface enable-animations
                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    # Clock Settings
                    gsettings set org.gnome.desktop.interface clock-format '12h'
                    gsettings set org.gnome.desktop.interface clock-show-date true
                    gsettings set org.gnome.desktop.interface clock-show-seconds false
                    gsettings set org.gnome.desktop.interface clock-show-weekday false

                    # No hot corners
                    gsettings set org.gnome.desktop.interface enable-hot-corners false

                    # Emacs please
                    gsettings set org.gnome.desktop.interface gtk-key-theme 'Emacs'

                    # Show battery
                    gsettings set org.gnome.desktop.interface show-battery-percentage true

                    # Enable window buttons
                    gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'

                    # Set new windows centered
                    gsettings set org.gnome.mutter center-new-windows true

                    # Set list-view for Nautilius
                    gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'

                    # Force alt + tab to switch only on current workspace
                    gsettings set org.gnome.shell.app-switcher current-workspace-only true

                    # Set fractional scaling (only for wayland)
                    # gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"

                    # Stop Gnome Software downloading updates
                    # gsettings set org.gnome.software allow-updates false
                    # gsettings set org.gnome.software download-updates false
                    # gsettings set org.gnome.software download-updates-notify false
                fi

                read -rp "$CHOICE) Defaults has been set. Press enter to continue..."
                ;;
            6)
                echo "$CHOICE) Installing Needed Software"

                # Setup zram (even with swap zram will have a higher priority)
                if ! test "$(cat /proc/swaps | grep /dev/zram)"; then
                    sudo zypper in -y systemd-zram-service
                    echo -e "\n#Custom Settings" | sudo tee -a /etc/sysctl.conf
                    echo -e "\nvm.vfs_cache_pressure=500 # increase frequency of clearing caches to free RAM" | sudo tee -a /etc/sysctl.conf
                    echo -e "\nvm.swappiness=150 # increase percentage to start using zram earlier" | sudo tee -a /etc/sysctl.conf
                    echo -e "\nvm.dirty_background_ratio=1 # amount of memory pages permitted to be 'dirty' before writing to zram" | sudo tee -a /etc/sysctl.conf
                    echo -e "\nvm.dirty_ratio=50 # amount of memory pages permitted to be 'dirty' before writing to zram" | sudo tee -a /etc/sysctl.conf
                    sudo systemctl enable zramswap.service && sudo systemctl start zramswap.service
                fi

                read -rp "$CHOICE) Done. Press enter to continue..."
                ;;
            7)
                echo "$CHOICE) Installing General Software"

                # general
                sudo zypper install -y -t pattern devel_basis
                sudo zypper install -y -t pattern devel_C_C++
                sudo zypper install -y rpmdevtools make gcc-c++ gcc gdb automake autoconf autojump libtool
                sudo zypper install -y cmake ninja ccache meson
                sudo zypper install -y git ripgrep fd htop btop nvtop vim bat
                sudo zypper install -y aspell aspell-en aspell-es
                sudo zypper install -y curl dos2unix doxygen msmtp neofetch
                sudo zypper install -y graphviz mercurial password-store
                sudo zypper install -y pandoc poppler-tools poppler-data
                sudo zypper install -y subversion tree w3m wget texinfo
                sudo zypper install -y wordnet shfmt editorconfig ShellCheck
                sudo zypper install -y llvm clang clang-tools libpcap libpcap-devel
                sudo zypper install -y pkg-config openssl openssl-devel flex bison unar unrar unzip atool
                sudo zypper install -y ImageMagick ImageMagick-devel sqlite
                sudo zypper install -y feh mpv qrencode findutils
                sudo zypper install -y valgrind minicom mc strace tidy

                # Node
                sudo zypper install -y nodejs21 npm21

                # Wayland Software
                if [[ "$WINDOW_SYSTEM" == "$WS_WAYLAND" ]]; then
                    sudo zypper install -y wl-clipboard wayland-utils
                fi

                # X11 Software
                if [[ "$WINDOW_SYSTEM" == "$WS_X11" ]]; then
                    sudo zypper install -y xsel xclip xinput xdotool x11-utils
                fi

                # Gnome Software
                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    sudo zypper install -y dconf-editor gnome-tweaks
                fi

                # KDE Plasma Software
                if [[ "$WINDOW_MANAGER" == "$WM_KDE" ]]; then
                    sudo zypper install -y kdeconnect-kde
                    # sudo zypper install -y yakuake
                    # sudo zypper install -y latte-dock
                    # sudo zypper install -y kazam
                fi

                # lazygit: A simple terminal UI for git commands
                sudo zypper install -y lazygit

                # tmux: A terminal multiplexer
                sudo zypper install -y tmux

                # Alacritty - A fast, cross-platform, OpenGL terminal emulator
                sudo zypper install -y alacritty

                # foot - the fast, lightweight and minimalistic Wayland terminal emulator.
                [[ "$WINDOW_SYSTEM" == "$WS_WAYLAND" ]] && sudo zypper install -y foot

                # Starship Prompt
                curl -sS https://starship.rs/install.sh | sh

                # gpg
                sudo zypper install -y pcsc-tools opensc pcsc-lite pcsc-ccid
                sudo systemctl enable pcscd && sudo systemctl start pcscd

                # yubikey
                sudo zypper install -y yubikey-manager

                # ncdu (text-based disk usage viewer)
                sudo zypper install -y ncdu

                # Borg Backup
                sudo zypper install -y borgbackup

                # Command Line Fuzzy Finder
                sudo zypper install -y fzf

                # Neovim
                sudo zypper install -y neovim python3-neovim

                # profile sync daemon
                sudo zypper install -y profile-sync-daemon
                if [ -f /usr/share/psd/contrib/brave ]; then
                    sudo cp /usr/share/psd/contrib/brave /usr/share/psd/browsers
                elif [ -f "$HOME"/Workspace/Public/dotfiles/Common/psd/brave ]; then
                    sudo cp "$HOME"/Workspace/Public/dotfiles/Common/psd/brave /usr/share/psd/browsers
                fi
                systemctl --user enable psd.service && systemctl --user start psd.service

                # non zypper software
                pip install cmake-language-server --break-system-packages
                pip install pyright --break-system-packages
                sudo npm install --global npm@latest
                sudo npm install --global prettier
                sudo npm install --global js-beautify
                sudo npm install --global typescript-language-server typescript
                sudo npm install --global dockerfile-language-server-nodejs
                sudo npm install --global bash-language-server

                read -rp "$CHOICE) General software has been installed. Press enter to continue..."
                ;;
            8)
                echo "$CHOICE) Installing Extras"

                #
                # Multimedia codecs
                #
                sudo zypper install -y opi
                opi codecs

                #
                # Wireguard
                #
                # sudo zypper install -y wireguard-tools

                #
                # Docker
                #
                # Install and Enable Docker
                sudo zypper install -y docker
                sudo systemctl enable docker && sudo systemctl start docker

                # add user
                sudo usermod -G docker -a "$USER"
                sudo systemctl restart docker

                # test we can run docker without `sudo`
                # docker run hello-world

                #
                # Latex
                #
                # sudo zypper install -y texlive-scheme-full
                sudo zypper install -y texlive-scheme-basic

                #
                # Fonts
                #
                # sudo zypper install -y iosevka-fonts jetbrains-mono-fonts adobe-sourcecodepro-fonts
                sudo zypper install -y fetchmsttfonts
                install_berkeley_mono_font
                install_iosevka_comfy_font
                install_monaspace_font

                read -rp "$CHOICE) Extras installed. Press enter to continue..."
                ;;
            9)
                echo "$CHOICE) Enabling Flatpak"

                sudo zypper install -y flatpak
                flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
                flatpak update
                # if [[ "$WINDOW_MANAGER" == "$WM_KDE" ]]; then
                #     sudo zypper install -y plasma-discover-backend-flatpak
                # fi
                if [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]]; then
                    sudo zypper install -y gnome-software-plugin-flatpak
                    flatpak install --user -y flathub org.gnome.TextEditor
                    flatpak install --user -y flathub org.gnome.Firmware
                    flatpak install --user -y flathub com.mattjakeman.ExtensionManager
                fi
                flatpak install --user -y flathub com.discordapp.Discord
                flatpak install --user -y flathub com.dropbox.Client
                flatpak install --user -y flathub com.slack.Slack
                flatpak install --user -y flathub org.videolan.VLC
                flatpak install --user -y flathub com.transmissionbt.Transmission
                flatpak install --user -y flathub org.wireshark.Wireshark
                flatpak install --user -y flathub com.github.tchx84.Flatseal          # manage flatpak permisions
                flatpak install --user -y flathub io.github.Hexchat                   # irc client
                flatpak install --user -y flathub engineer.atlas.Nyxt
                # flatpak install --user -y flathub org.mozilla.firefox
                # flatpak install --user -y flathub org.telegram.desktop
                # flatpak install --user -y flathub org.gnucash.GnuCash
                # flatpak install --user -y flathub org.gimp.GIMP
                # flatpak install --user -y flathub com.skype.Client
                # flatpak install --user -y flathub com.valvesoftware.Steam
                # flatpak install --user -y flathub im.riot.Riot
                # flatpak install --user -y flathub org.keepassxc.KeePassXC
                # flatpak install --user -y flathub com.obsproject.Studio
                # flatpak install --user -y flathub com.brave.Browser
                # flatpak install --user -y flathub org.shotcut.Shotcut
                # flatpak install --user -y flathub dev.geopjr.Tuba
                # flatpak install --user -y flathub io.github.mimbrero.WhatsAppDesktop
                # flatpak install --user -y flathub org.signal.Signal
                # flatpak install --user -y flathub com.microsoft.Edge
                # flatpak install --user -y flathub com.visualstudio.code
                # flatpak install --user -y flathub com.github.GradienceTeam.Gradience

                read -rp "$CHOICE) Flatpak has now been enabled. Press enter to continue..."
                ;;
            10)
                echo "$CHOICE) Setting up secrets and repos"

                read -rp "Enter keys backup directory: " KEYS_DIR
                KEYS_DIR=${KEYS_DIR%/}
                [ ! -d "$KEYS_DIR" ] && notify-send "$KEYS_DIR is not a directory" --expire-time=20 && continue
                [ ! -f "$(pwd)/../scripts/+crypt" ] && notify-send "$(pwd)/../scripts/+crypt script does not exists" --expire-time=20 && continue
                [ ! -f "$KEYS_DIR/ssh.tar.gz.gpg" ] && notify-send "$KEYS_DIR/ssh.tar.gz.gpg does not exists" --expire-time=20 && continue
                [ ! -f "$KEYS_DIR/gpg.tar.gz.gpg" ] && notify-send "$KEYS_DIR/gpg.tar.gz.gpg does not exists" --expire-time=20 && continue

                echo ">> Setting up ssh keys from $KEYS_DIR/ssh.tar.gz.gpg"
                "$(pwd)/../scripts/+crypt" -d "$KEYS_DIR/ssh.tar.gz.gpg"
                [ ! -d "$KEYS_DIR"/ssh ] && notify-send "Decryption failed, $KEYS_DIR/ssh does not exists" --expire-time=20 && continue
                mkdir -p ~/.ssh && rm -rf ~/.ssh/*
                cp "$KEYS_DIR"/ssh/id_* ~/.ssh
                cp "$KEYS_DIR"/ssh/config ~/.ssh
                chmod 700 ~/.ssh
                chmod 644 ~/.ssh/config
                chmod 600 ~/.ssh/id_*
                chmod 644 ~/.ssh/id_*.pub
                rm -rf "$KEYS_DIR"/ssh

                echo ">> Setting up gpg keys from $KEYS_DIR/gpg.tar.gz.gpg"
                "$(pwd)/../scripts/+crypt" -d "$KEYS_DIR/gpg.tar.gz.gpg"
                [ ! -d "$KEYS_DIR"/gpg ] && notify-send "Decryption failed, $KEYS_DIR/gpg does not exists" --expire-time=20 && continue
                mkdir -p ~/.gnupg && rm -rf ~/.gnupg/*
                cp "$KEYS_DIR"/gpg/config/*.conf ~/.gnupg
                gpg --import "$KEYS_DIR"/gpg/new_keys/0xB3F739419D91C7F3-2022-09-28.pub.asc
                rm -rf "$KEYS_DIR"/gpg

                echo "Editing gpg key 0xB3F..., you should 'trust' ultimately (Option 5) and 'quit'"
                gpg --edit-key 0xB3F739419D91C7F3

                # Remove keys
                rm -rf "$KEYS_DIR"

                # With the new keys we can go ahead and download some repos
                [ ! -d "$HOME/.password-store" ] && git clone git@github.com:jvillasante/pass.git "$HOME"/.password-store
                [ ! -d "$HOME"/Workspace/Public/dotfiles ] && git clone git@github.com:jvillasante/dotfiles.git "$HOME"/Workspace/Public/dotfiles
                [ ! -d "$HOME"/Workspace/Public/resume ] && git clone git@github.com:jvillasante/resume.git "$HOME"/Workspace/Public/resume

                read -rp "$CHOICE) Secrets and repos are set. Press enter to continue..."
                ;;
            11)
                echo "$CHOICE) Installing Emacs"

                # Is it already installed?
                hash emacs 2> /dev/null && notify-send "Emacs is already installed" --expire-time=20 && continue

                # Install dependencies
                sudo zypper install -y libgccjit0 libgccjit0-devel
                sudo zypper install -y gtk3 gtk3-devel gtk4 gtk4-devel libgnutls-devel libxml2-devel libjansson-devel giflib-devel \
                     libtiff-devel libotf-devel libvterm-devel
                sudo zypper install -y tree-sitter tree-sitter-devel # treesitter
                sudo zypper install -y enchant-devel pkgconf # jinx

                # Prepare git repo
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                if [ ! -d "$HOME"/Workspace/Software/emacs ]; then
                    git clone git://git.sv.gnu.org/emacs.git "$HOME"/Workspace/Software/emacs
                    pushd "$HOME"/Workspace/Software/emacs || {
                        notify-send "Can't cd into $HOME/Workspace/Software/emacs" --expire-time=20
                        continue
                    }
                else
                    pushd "$HOME"/Workspace/Software/emacs || {
                        notify-send "Can't cd into $HOME/Workspace/Software/emacs" --expire-time=20
                        continue
                    }

                    sudo make uninstall
                    make clean && make distclean
                    git reset --hard HEAD
                    sudo git clean -dfx
                    git pull
                fi

                # Build (emacs-29)
                git checkout emacs-29
                ./autogen.sh

                # Install
                EMACS_WINDOW_SYSTEM_OPTION=--with-x
                [[ "$WINDOW_SYSTEM" == "$WS_WAYLAND" ]] && EMACS_WINDOW_SYSTEM_OPTION=--with-pgtk
                ./configure \
                    $EMACS_WINDOW_SYSTEM_OPTION \
                    --without-compress-install \
                    --with-native-compilation=aot \
                    --with-tree-sitter \
                    --with-json \
                    --with-mailutils \
                    CFLAGS="-O3 -mtune=native -march=native -fomit-frame-pointer" prefix=/usr/local
                make -j"$(nproc --ignore=2)"
                sudo make install

                popd || notify-send "Can't cd to previous directory" --expire-time=20
                read -rp "$CHOICE) Emacs has been installed. Press enter to continue..."
                ;;
            12)
                echo "$CHOICE) Installing Keyd"

                # Is it already installed?
                hash keyd 2> /dev/null && notify-send "Keyd is already installed" --expire-time=20 && continue

                # Prepare git repo
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                if [ ! -d "$HOME"/Workspace/Software/keyd ]; then
                    git clone git@github.com:rvaiya/keyd.git "$HOME"/Workspace/Software/keyd
                    pushd "$HOME"/Workspace/Software/keyd || {
                        notify-send "Can't cd into $HOME/Workspace/Software/keyd" --expire-time=20
                        continue
                    }
                else
                    pushd "$HOME"/Workspace/Software/keyd || {
                        notify-send "Can't cd into $HOME/Workspace/Software/keyd" --expire-time=20
                        continue
                    }

                    sudo make uninstall
                    make clean && make distclean
                    git reset --hard HEAD
                    sudo git clean -dfx
                    git pull
                fi

                # Install
                make -j"$(nproc --ignore=2)"
                sudo make install

                # Copy Configuration
                sudo cp "$HOME"/Workspace/Public/dotfiles/Common/keyd/default.conf /etc/keyd/default.conf

                # Add yourself to the keyd group
                sudo usermod -aG keyd -a "$USER"

                # Enable the daemon
                sudo systemctl daemon-reload
                sudo systemctl enable keyd && sudo systemctl start keyd
                sudo keyd reload

                popd || notify-send "Can't cd to previous directory" --expire-time=20
                read -rp "$CHOICE) Keyd daemon has been installed. Press enter to continue..."
                ;;
            13)
                echo "$CHOICE) Installing Xkeysnail"
                notify-send "Using xremap at the moment" --expire-time=20
                continue

                # Only works on X11
                [[ "$WINDOW_SYSTEM" != "$WS_X11" ]] && notify-send "Xkeysnail only supports X11" --expire-time=20 && continue

                # Is it already installed?
                hash xkeysnail 2> /dev/null && notify-send "Xkeysnail is already installed" --expire-time=20 && continue

                # Prepare git repo
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                if [ ! -d "$HOME"/Workspace/Software/xkeysnail ]; then
                    git clone --depth 1 git@github.com:mooz/xkeysnail.git "$HOME"/Workspace/Software/xkeysnail
                    pushd "$HOME"/Workspace/Software/xkeysnail || {
                        notify-send "Can't cd into $HOME/Workspace/Software/xkeysnail" --expire-time=20
                        continue
                    }
                else
                    pushd "$HOME"/Workspace/Software/xkeysnail || {
                        notify-send "Can't cd into $HOME/Workspace/Software/xkeysnail" --expire-time=20
                        continue
                    }

                    sudo pip3 uninstall . --break-system-packages
                    git reset --hard HEAD
                    sudo git clean -dfx
                    git pull
                fi

                # Install
                sudo pip3 install --upgrade . --break-system-packages

                ## Run without sudo
                # First create a new group to which we allow access to the input stuff, and add this group to your user:
                sudo groupadd -f uinput
                sudo gpasswd -a "$USER" uinput

                # Second Create new udev rule granting access:
                sudo cp -f "$HOME"/Workspace/Public/dotfiles/Common/xkeysnail/udev/70-xkeysnail.rules /etc/udev/rules.d/70-xkeysnail.rules

                # Enable the daemon
                mkdir -p ~/.config/systemd/user/
                [ -L "$HOME/.config/systemd/user/xkeysnail.service" ] && unlink "$HOME/.config/systemd/user/xkeysnail.service"
                ln -s "$HOME/Workspace/Public/dotfiles/Common/systemd/user/xkeysnail.service" "$HOME/.config/systemd/user"
                systemctl --user daemon-reload
                systemctl --user enable xkeysnail.service && systemctl --user start xkeysnail.service

                popd || notify-send "Can't cd to previous directory" --expire-time=20
                read -rp "$CHOICE) Xkeysnail has been installed. Reboot is necessary for udev rules to take effect. Press enter to continue..."
                ;;
            14)
                echo "$CHOICE) Installing Xremap"

                [[ "$WINDOW_SYSTEM" == "$WS_X11" ]] && sudo zypper install -y libx11-dev

                # Is it already installed?
                hash xremap 2> /dev/null && notify-send "Xremap is already installed" --expire-time=20 && continue

                # Install
                [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
                [ ! -d "$HOME"/Workspace/Software/xremap ] && mkdir -p "$HOME"/Workspace/Software/xremap

                pushd "$HOME"/Workspace/Software/xremap || {
                        notify-send "Can't cd into $HOME/Workspace/Software/xremap" --expire-time=20
                        continue
                }

                XREMAP_VERSION=v0.8.14
                XREMAP_RELEASE=xremap-linux-x86_64-kde.zip
                [[ "$WINDOW_MANAGER" == "$WM_GNOME" ]] && XREMAP_RELEASE=xremap-linux-x86_64-gnome.zip

                curl -LJO https://github.com/k0kubun/xremap/releases/download/"$XREMAP_VERSION"/"$XREMAP_RELEASE"
                atool --extract --explain "$XREMAP_RELEASE"
                sudo cp -f xremap /usr/local/bin/

                popd || {
                        notify-send "Can't cd to previous directory" --expire-time=20
                        continue
                }

                # First create a new group to which we allow access to the input stuff, and add this group to your user:
                sudo groupadd -f uinput
                sudo gpasswd -a "$USER" uinput

                # Second Create new udev rule granting access:
                sudo cp -f "$HOME"/Workspace/Public/dotfiles/Common/xremap/udev/70-xremap.rules /etc/udev/rules.d/70-xremap.rules

                # Enable the daemon
                [ ! -d "$HOME"/.config/systemd/user ] && mkdir -p "$HOME"/.config/systemd/user
                [ -L "$HOME/.config/systemd/user/xremap.service" ] && unlink "$HOME/.config/systemd/user/xremap.service"
                ln -s "$HOME/Workspace/Public/dotfiles/Common/systemd/user/xremap.service" "$HOME/.config/systemd/user"
                systemctl --user daemon-reload
                systemctl --user enable xremap.service && systemctl --user start xremap.service

                read -rp "$CHOICE) Xremap has been installed. Reboot is necessary for udev rules to take effect. Press enter to continue..."
                ;;
            15)
                exit 0
                ;;
        esac
    done
}

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

if [ ! -f /etc/products.d/openSUSE.prod ]; then
    echo "Error: OpenSuse is not running on this system, exiting..."
    exit 1
fi

if ! hash zypper 2> /dev/null; then
    echo "Error: zypper not installed on this system, exiting..."
    exit 1
fi

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    install)
        [ "$nargs" -eq 1 ] || usage 1
        suse_install "$@"
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
