#!/usr/bin/env bash

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 update:"
    echo "        Update Debian System"
    echo "    $0 apt [arbitrary APT command]:"
    echo "        Run arbitrary APT command"
    echo
    echo " e.g: $0 apt full-upgrade"
    exit "$1"
}

debian_update() {
    sudo apt update -y
    test $? -eq 0 || usage 1

    sudo apt upgrade -y
    test $? -eq 0 || usage 1

    sudo apt full-upgrade
    test $? -eq 0 || usage 1

    sudo apt autoremove
    test $? -eq 0 || usage 1

    sudo flatpak update -y
    test $? -eq 0 || usage 1
}

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

if [[ ! -f /etc/debian_version ]]; then
    echo "Error: Debian is not running on this system, exiting..."
    exit 1
fi

if ! hash apt 2>/dev/null; then
    echo "Error: apt not installed on this system, exiting..."
    exit 1
fi

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    update)
        [[ "$nargs" -eq 1 ]] || usage 1
        debian_update "$@"
        ;;
    apt)
        [[ "$nargs" -lt 2 ]] && usage 1
        apt "$@"
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
