#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

. "$HOME/.config/shell/system/common.sh"
DOTFILES_DIR="$(find_dotfiles)"

tmuxifier load-window "$DOTFILES_DIR/Common/shell/tmuxifier/DmxsWindow.sh"
tmux send-keys C-u "$1" Enter
