#!/usr/bin/env bash

#
# This is how I manage my dotfiles
#

. "$HOME/.config/shell/common.sh"
DOTFILES_DIR="$(find_dotfiles)"

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 dotfiles [pull | sync]:"
    echo "        Update personal dotfiles (pull from remote or sync on local)"
    echo "    $0 doom [restart | arbitrary doom command]:"
    echo "        Run arbitrary doom command"
    echo "    $0 emacs kill"
    echo "        Kill emacs daemon"
    echo
    echo " e.g: $0 doom -y sync"
    exit "$1"
}

do_dotfiles() {
    case $1 in
        pull)
            if [ -d "$DOTFILES_DIR" ]; then
                git -C "${DOTFILES_DIR}" status
                test $? -eq 0 || usage 1

                if ask "Do you want to pull?"; then
                    git -C "${DOTFILES_DIR}" pull
                    test $? -eq 0 || usage 1
                fi
            fi
            ;;
        sync)
            if [ ! -f "${DOTFILES_DIR}/make.sh" ]; then
                echo "${DOTFILES_DIR}/make.sh script not present, exiting..." && usage 1
            fi

            "${DOTFILES_DIR}/make.sh"
            test $? -eq 0 || usage 1
            ;;
        *)
            usage 1
            ;;
    esac
}

do_emacs() {
    case $1 in
        kill)
            if pgrep emacs >/dev/null; then
                emacsclient --eval '(save-buffers-kill-emacs)'
                test $? -eq 0 || usage 1
            fi
            ;;
        *)
            usage 1
            ;;
    esac
}

do_doom() {
    if [ ! -f "$DOTFILES_DIR/.emacs.doom/bin/doom" ]; then
        echo "doom script not present, exiting..." && usage 1
    fi

    case $1 in
        restart)
            env EMACSDIR="$DOTFILES_DIR/.emacs.doom" \
                env DOOMDIR="$DOTFILES_DIR/Common/emacs/doom" \
                "$DOTFILES_DIR/.emacs.doom/bin/doom" sync
            do_emacs "kill"
            echo "> Done."
            ;;
        *)
            env EMACSDIR="$DOTFILES_DIR/.emacs.doom" \
                env DOOMDIR="$DOTFILES_DIR/Common/emacs/doom" \
                "$DOTFILES_DIR/.emacs.doom/bin/doom" "$@"
            echo "> Done."
            ;;
    esac
}

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    dotfiles)
        [ "$nargs" -eq 2 ] || usage 1
        do_dotfiles "$@"
        ;;
    chemacs)
        [ "$nargs" -eq 2 ] || usage 1
        do_chemacs "$@"
        ;;
    doom)
        [ "$nargs" -lt 2 ] && usage 1
        do_doom "$@"
        ;;
    emacs)
        [ "$nargs" -eq 2 ] || usage 1
        do_emacs "$@"
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
