#!/usr/bin/env bash

# +emux.sh top - runs top inside your active Emacs instance.
# +emus.sh watch free -hg - calls watch and tells it to run free -hg.
# +emux.sh - on its own will call your $SHELL instead.

set -o nounset -o errexit -o pipefail

argcmd="$@"
cmd="${argcmd:=$SHELL}"
exec emacsclient -e <<EOF
(let ((vterm-shell "${cmd}")) (if (fboundp 'vterm) (vterm t) (term vterm-shell)))
EOF
