#!/usr/bin/env bash

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 update:"
    echo "        Update Fedora System"
    echo "    $0 dnf [arbitrary DNF command]:"
    echo "        Run arbitrary DNF command"
    echo
    echo " e.g: $0 dnf check-update"
    exit "$1"
}

fedora_update() {
    sudo dnf -y --refresh upgrade
    test $? -eq 0 || usage 1

    sudo dnf -y distro-sync
    test $? -eq 0 || usage 1

    sudo dnf -y autoremove
    test $? -eq 0 || usage 1

    sudo flatpak update -y
    test $? -eq 0 || usage 1
}

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

if [[ ! -f /etc/fedora-release ]]; then
    echo "Error: Fedora is not running on this system, exiting..."
    exit 1
fi

if ! hash dnf 2>/dev/null; then
    echo "Error: dnf not installed on this system, exiting..."
    exit 1
fi

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    update)
        [[ "$nargs" -eq 1 ]] || usage 1
        fedora_update "$@"
        ;;
    dnf)
        [[ "$nargs" -lt 2 ]] && usage 1
        dnf "$@"
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
