#!/usr/bin/env bash

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 install:"
    echo "        Install Fedora System"
    echo "    $0 update:"
    echo "        Update Fedora System"
    echo "    $0 dnf [arbitrary DNF command]:"
    echo "        Run arbitrary DNF command"
    echo
    echo " e.g: $0 dnf check-update"
    exit "$1"
}

fedora_install() {
    HEIGHT=20
    WIDTH=90
    CHOICE_HEIGHT=4
    BACKTITLE="Fedora Setup Util"
    TITLE="Please Make a selection"
    MENU="Please Choose one of the following options:"

    # Check to see if Dialog is installed, if not install it
    if [ "$(rpm -q dialog 2>/dev/null | grep -c "is not installed")" -eq 1 ]; then
        sudo dnf install -y dialog
    fi

    OPTIONS=(
        1 "Speed up DNF - This enables fastestmirror, max downloads and deltarpms"
        2 "Enable RPM Fusion - Enables the RPM Fusion repos for your specific version"
        3 "Update Firmware - fw firmware update (reboot needed)"
        4 "Install NVIDIA - Install NVIDIA Drivers (reboot needed)"
        5 "Install Software - Installs a bunch of my most used software"
        6 "Install Extras - Themes Fonts and Codecs"
        7 "Enable Flatpak - Enables the Flatpak repo and installs packages"
        8 "Install Docker - Install docker"
        9 "Set Defaults - Set some defaults (hostname, gsettings, etc)"
        10 "Install Nix - The Nix package manager"
        11 "Quit")

    while true; do
        CHOICE=$(dialog --clear \
            --backtitle "$BACKTITLE" \
            --title "$TITLE" \
            --nocancel \
            --menu "$MENU" \
            $HEIGHT $WIDTH $CHOICE_HEIGHT \
            "${OPTIONS[@]}" \
            2>&1 >/dev/tty)

        clear
        case $CHOICE in
            1)
                echo "1) Speeding Up DNF"
                echo 'fastestmirror=1' | sudo tee -a /etc/dnf/dnf.conf
                echo 'max_parallel_downloads=10' | sudo tee -a /etc/dnf/dnf.conf
                echo 'deltarpm=true' | sudo tee -a /etc/dnf/dnf.conf

                notify-send "1) DNF config has now been amended" --expire-time=20
                ;;
            2)
                echo "2) Enabling RPM Fusion"
                sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-"$(rpm -E %fedora)".noarch.rpm
                sudo dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-"$(rpm -E %fedora)".noarch.rpm
                sudo dnf upgrade --refresh
                sudo dnf groupupdate -y core
                sudo dnf install -y rpmfusion-free-release-tainted
                sudo dnf install -y rpmfusion-nonfree-release-tainted
                sudo dnf install -y dnf-plugins-core

                notify-send "2) RPM Fusion has been enabled" --expire-time=20
                ;;
            3)
                echo "3) Updating Firmware"
                sudo dnf upgrade --refresh
                sudo dnf check
                sudo dnf autoremove
                sudo fwupdmgr get-devices
                sudo fwupdmgr refresh --force
                sudo fwupdmgr get-updates
                sudo fwupdmgr update

                notify-send "3) Latest Firmware installed" "Please reboot to finalize driver installation." --expire-time=5000
                ;;
            4)
                echo "4) Installing NVIDIA Drivers"
                sudo dnf install -y akmod-nvidia
                sudo dnf install -y xorg-x11-drv-nvidia xorg-x11-drv-nvidia-libs
                sudo dnf install -y xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia-cuda-libs # To support ffmpeg compiled with NVENC/NVDEC
                sudo dnf install -y vdpauinfo libva-vdpau-driver libva-utils               # For hardware video acceleration
                sudo dnf install -y vulkan vulkan-tools                                    # Installs support for Vulkan which has the same functionality as openGL

                notify-send "4) NVIDIA drivers installed" "Please reboot to finalize driver installation." --expire-time=5000
                ;;
            5)
                echo "5) Installing Software"
                # general
                sudo dnf install -y dnf-plugins-core copr-cli
                sudo dnf groupinstall -y "Development Tools" "Development Libraries"
                sudo dnf install -y git ripgrep fd-find xclip util-linux-user xprop xwininfo
                sudo dnf install -y aspell aspell-en aspell-es autojump atool autoconf automake bat cmake vim htop
                sudo dnf install -y freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel
                sudo dnf install -y curl dconf-editor dnsutils dos2unix doxygen msmtp neofetch
                sudo dnf install -y graphviz htop mercurial exa ninja-build pass
                sudo dnf install -y nodejs npm python3 python3-pip pandoc poppler-utils poppler-data
                sudo dnf install -y subversion tldr tmux tree unzip w3m wget libtool ranger texinfo
                sudo dnf install -y wordnet shfmt editorconfig glslang ShellCheck xdotool parallel
                sudo dnf install -y llvm clang clang-tools-extra libpcap libpcap-devel
                sudo dnf install -y pkg-config openssl openssl-devel flex bison unar unrar p7zip p7zip-plugins
                sudo dnf install -y gimp vlc transmission gparted tidy
                sudo dnf install -y ImageMagick ImageMagick-devel sqlite zeal scrot
                sudo dnf install -y go valgrind minicom mc strace

                # Wayland stuff
                sudo dnf install -y egl-wayland egl-wayland-devel wl-clipboard

                # tmux: A terminal multiplexer
                sudo dnf install -y tmux

                # Alacritty
                sudo dnf install -y alacritty

                # Starship Prompt
                curl -sS https://starship.rs/install.sh | sh

                # gpg
                sudo dnf install -y gpg gnupg2 gnupg-pkcs11-scd pcsc-tools opensc pcsc-lite-ccid
                sudo systemctl enable pcscd
                sudo systemctl start pcscd
                sudo systemctl restart pcscd

                # yubikey
                sudo dnf install -y yubikey-manager
                ykman info

                # ncdu (text-based disk usage viewer)
                sudo dnf install -y ncdu

                # Wireshark
                sudo dnf install -y wireshark wireshark-cli

                # Borg Backup
                sudo dnf install -y borgbackup

                # Command Line Fuzzy Finder
                sudo dnf install -y skim

                # Gnome Software
                sudo dnf -y install gnome-tweaks gnome-firmware gnome-extensions-app gnome-shell-extension-appindicator

                # Neovim nightly
                sudo dnf copr enable agriffis/neovim-nightly -y
                sudo dnf install -y neovim python3-neovim

                # Firewall GUI to manage firewalld
                sudo dnf install -y firewall-config

                # Profile sync daemon
                sudo dnf install -y profile-sync-daemon
                sudo cp /usr/share/psd/contrib/brave /usr/share/psd/browsers
                systemctl --user enable psd.service
                systemctl --user start psd.service
                systemctl --user restart psd.service

                # Brave Browser
                sudo dnf install -y dnf-plugins-core
                sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
                sudo rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
                sudo dnf update -y
                sudo dnf install -y brave-browser

                # non dnf software
                pip install cmake-language-server
                sudo npm install --global npm@latest
                sudo npm install --global prettier
                sudo npm install --global js-beautify
                sudo npm install --global typescript-language-server typescript
                sudo npm install --global dockerfile-language-server-nodejs
                sudo npm install --global bash-language-server

                notify-send "5) Software has been installed" --expire-time=20
                ;;
            6)
                echo "6) Installing Extras"
                # Multimedia
                sudo dnf groupupdate -y sound-and-video
                sudo dnf install -y libdvdcss
                sudo dnf install -y \
                    gstreamer1-plugins-{bad-\*,good-\*,ugly-\*,base} gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel \
                    ffmpeg gstreamer-ffmpeg
                sudo dnf install -y lame\* --exclude=lame-devel
                sudo dnf group upgrade -y --with-optional Multimedia

                # Fonts
                sudo dnf -y copr enable peterwu/iosevka
                sudo dnf -y copr enable dawid/better_fonts
                sudo dnf update -y
                sudo dnf install -y fontconfig-font-replacements
                sudo dnf install -y fontconfig-enhanced-defaults
                sudo dnf update -y
                sudo dnf install -y libreoffice-opensymbol-fonts
                sudo dnf install -y adobe-source-code-pro-fonts
                sudo dnf install -y jetbrains-mono-fonts-all
                sudo dnf install -y ibm-plex-mono-fonts ibm-plex-sans-fonts ibm-plex-serif-fonts
                sudo dnf install -y iosevka-fonts iosevka-fixed-fonts iosevka-term-fonts iosevka-slab-fonts iosevka-aile-fonts
                sudo dnf install -y terminus-fonts terminus-fonts-console google-noto-fonts-common mscore-fonts-all fira-code-fonts

                # Latex
                # sudo dnf install -y texlive-scheme-full

                notify-send "6) Multimedia, fonts and others has been installed" --expire-time=20
                ;;
            7)
                echo "7) Enabling Flatpak"
                flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
                flatpak update
                flatpak install -y "com.dropbox.Client"
                flatpak install -y "com.discordapp.Discord"
                flatpak install -y "com.skype.Client"
                flatpak install -y "com.slack.Slack"
                flatpak install -y "org.telegram.desktop"
                flatpak install -y "org.signal.Signal"
                flatpak install -y "com.visualstudio.code"

                notify-send "7) Flatpak has now been enabled" --expire-time=20
                ;;

            8)
                echo "8) Installing Docker"
                sudo dnf install -y dnf-plugins-core
                sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
                sudo dnf install -y docker-ce docker-ce-cli containerd.io

                sudo systemctl enable docker
                sudo systemctl start docker
                sudo docker run hello-world

                notify-send "8) Docker has been installed" --expire-time=20
                ;;
            9)
                echo "9) Setting Defaults"
                # hostname
                read -r -p "Enter pretty hostname (defaults to 'Julio's Personal Laptop'): " HOSTNAME_PRETTY
                [ -z "$HOSTNAME_PRETTY" ] && HOSTNAME_PRETTY="Julio's Personal Laptop"
                sudo hostnamectl set-hostname --pretty "$HOSTNAME_PRETTY"

                read -r -p "Enter static hostname (defaults to 'fedora-xps-9710'): " HOSTNAME_STATIC
                [ -z "$HOSTNAME_STATIC" ] && HOSTNAME_STATIC="fedora-xps-9710"
                sudo hostnamectl set-hostname --static "$HOSTNAME_STATIC"

                # xdg
                export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
                export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
                export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
                export XDG_LIB_HOME="${XDG_DATA_HOME:-$HOME/.local/lib}"
                export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
                mkdir -p \
                    "${XDG_CACHE_HOME}" \
                    "${XDG_CONFIG_HOME}" \
                    "${XDG_DATA_HOME}" \
                    "${XDG_LIB_HOME}" \
                    "${XDG_STATE_HOME}"

                # View current settings - gsettings list-recursively org.gnome.desktop.interface
                # Font Settings
                gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans 11'
                gsettings set org.gnome.desktop.interface font-name 'Noto Sans 11'
                gsettings set org.gnome.desktop.interface monospace-font-name 'JetBrains Mono 12'
                gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Noto Sans 11'

                # Other Settings
                gsettings set org.gnome.desktop.interface clock-format '24h'
                gsettings set org.gnome.desktop.interface clock-show-date true
                gsettings set org.gnome.desktop.interface clock-show-seconds false
                gsettings set org.gnome.desktop.interface clock-show-weekday false

                # Enable window buttons
                gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"

                # Set new windows centered
                gsettings set org.gnome.mutter center-new-windows true

                notify-send "9) Defaults has been set" --expire-time=20
                ;;
            10)
                if [ "$(getenforce 2>/dev/null | grep -c "Enforcing")" -eq 1 ]; then
                    notify-send "10) I won't install Nix" "It does not work with SELinux" --expire-time=20
                    continue
                fi

                # Install nix
                if ! hash nix 2>/dev/null; then
                    echo "install: setting up nix..."
                    sh <(curl -L https://nixos.org/nix/install) --daemon

                    # Set current user as trusted user
                    echo "trusted-users = root ${USER}" | sudo tee -a /etc/nix/nix.conf && sudo pkill nix-daemon

                    source "$HOME/.bashrc"

                    nix-channel --add https://nixos.org/channels/nixpkgs-unstable
                fi

                nix-channel --update

                # Install cachix (https://www.cachix.org/)
                if ! hash cachix 2>/dev/null; then
                    echo "install: setting up cachix..."

                    # Check to see if curl is installed, if not install it
                    if [ "$(rpm -q curl 2>/dev/null | grep -c "is not installed")" -eq 1 ]; then
                        sudo dnf install -y curl
                    fi

                    nix-env -iA cachix -f https://cachix.org/api/v1/install
                fi

                # Using `https://devenv.sh/` alternative would be `https://github.com/nix-community/nix-direnv`
                # Install devenv
                if ! hash devenv 2>/dev/null; then
                    nix-env -if https://github.com/cachix/devenv/tarball/latest
                fi

                notify-send "10) Nix has been installed" --expire-time=20
                ;;
            11)
                exit 0
                ;;
        esac
    done
}

fedora_update() {
    sudo dnf -y upgrade --refresh
    test $? -eq 0 || usage 1

    sudo dnf -y distro-sync
    test $? -eq 0 || usage 1

    sudo dnf autoremove
    test $? -eq 0 || usage 1

    flatpak update
    test $? -eq 0 || usage 1
}

if [ ! -f /etc/fedora-release ]; then
    echo "Error: Fedora is not running on this system, exiting..."
    exit 1
fi

if ! hash dnf 2>/dev/null; then
    echo "Error: dnf not installed on this system, exiting..."
    exit 1
fi

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    install)
        [ "$nargs" -eq 1 ] || usage 1
        fedora_install "$@"
        ;;
    update)
        [ "$nargs" -eq 1 ] || usage 1
        fedora_update "$@"
        ;;
    dnf)
        [ "$nargs" -lt 2 ] && usage 1
        dnf "$@"
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
