#!/usr/bin/env bash

. "$HOME/.config/shell/system/common.sh"

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 arkenfox:"
    echo "        Update firefox Default profile with arkenfox"
    echo "    $0 non-arkenfox:"
    echo "        Update firefox Default profile without arkenfox"
    echo "    e.g: $0 arkenfox"
    echo
    exit "$1"
}

firefox_default_profile() {
    local PROFILE_NAME
    PROFILE_NAME=$(grep "Default=.*\.default*" "$HOME/.mozilla/firefox/profiles.ini" | cut -d"=" -f2)
    [ -z "$PROFILE_NAME" ] && usage 1

    local PROFILE
    PROFILE="$HOME/.mozilla/firefox/$PROFILE_NAME"
    [ ! -d "$PROFILE" ] && usage 1

    echo "$PROFILE"
}

#
# https://github.com/arkenfox/user.js
#
update_arkenfox() {
    if pgrep -x firefox >/dev/null; then
        echo ">>> Firefox is running. Close Firefox and try again."
        usage 1
    fi

    local PROFILE
    PROFILE=$(firefox_default_profile)
    echo ">>> Updating 'user.js' file for $PROFILE"

    # Remove previous if any
    rm -rf /tmp/arkenfox-user.js-*

    # Get latest and update
    github_latest_release arkenfox user.js /tmp
    check $?

    cp -f /tmp/arkenfox-user.js-*/prefsCleaner.sh "${PROFILE}"
    check $?

    cp -f /tmp/arkenfox-user.js-*/updater.sh "${PROFILE}"
    check $?

    cp -f /tmp/arkenfox-user.js-*/user.js "${PROFILE}"
    check $?

    cat >"${PROFILE}/user-overrides.js" <<ENDOFFILE
// Re-enables 'about:home' page for startup landing page and new tabs.
/* 0102 */ user_pref("browser.startup.page", 1);
/* 0103 */ user_pref("browser.startup.homepage", "about:home");
/* 0104 */ user_pref("browser.newtabpage.enabled", true);
           user_pref("browser.newtab.preload", true);

// RFP is not for me
/* 4501 */ user_pref("privacy.resistFingerprinting", false);
/* 4504 */ user_pref("privacy.resistFingerprinting.letterboxing", false);
/* 4520 */ user_pref("webgl.disabled", false);

// Re-enables URL usages as a search bar.
/* 0801 */ user_pref("keyword.enabled", true);

// Enable live search suggestions
/* 0804 */ user_pref("browser.search.suggest.enabled", true);
           user_pref("browser.urlbar.suggest.searches", true);

// Don't throw away HTTP basic authentication sessions and history on Firefox shutdown.
/* 2811 */ user_pref("privacy.clearOnShutdown.sessions", false);
           user_pref("privacy.clearOnShutdown.history", false);

// Don't delete cookies and site data on exit (better to have site exceptions here!)
/* 2815 */ user_pref("privacy.clearOnShutdown.cookies", false);
           user_pref("privacy.clearOnShutdown.offlineApps", false);

// Disables Pocket extension.
/* 9000 */ user_pref("extensions.pocket.enabled", false);

// Personal, make tabbar height smaller
user_pref("browser.uidensity", 1);

// Personal, disable show menu on ALT press
user_pref("ui.key.menuAccessKeyFocuses", false);

/* END: internal custom pref to test for syntax errors ***/
user_pref("_user.js.parrot", "SUCCESS: No no he's not dead, he's, he's restin'!");
ENDOFFILE

    sh "${PROFILE}"/updater.sh -u -s
    check $?

    sh "${PROFILE}"/prefsCleaner.sh
    check $?

    echo ""
}

update_non_arkenfox() {
    if pgrep -x firefox >/dev/null; then
        echo ">>> Firefox is running. Close Firefox and try again."
        usage 1
    fi

    local PROFILE
    PROFILE=$(firefox_default_profile)
    echo ">>> Updating 'user.js' file for $PROFILE"

    cat >"${PROFILE}/user.js" <<ENDOFFILE
/*********************************************************************
*
* name: user.js
* descr.: Mozilla Firefox configuration file: 'user.js'
*
**********************************************************************/

// Disables Pocket extension.
user_pref("extensions.pocket.enabled", false);

// Make tabbar height smaller
user_pref("browser.uidensity", 1);

// Disable show menu on ALT press
user_pref("ui.key.menuAccessKeyFocuses", false);

/* END: internal custom pref to test for syntax errors ***/
user_pref("_user.js.parrot", "SUCCESS: No no he's not dead, he's, he's restin'!");
ENDOFFILE

    echo "All done!"
    echo ""
}

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    arkenfox)
        [ "$nargs" -eq 1 ] || usage 1
        update_arkenfox "$@"
        ;;
    non-arkenfox)
        [ "$nargs" -eq 1 ] || usage 1
        update_non_arkenfox "$@"
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
