#!/usr/bin/env bash

. "$HOME/.config/shell/common.sh"

install_common_go_packages() {
    if hash go 2>/dev/null; then
        # the go language server
        go install golang.org/x/tools/gopls@latest
        check $?

        # better than `go fmt`
        go install golang.org/x/tools/cmd/goimports@latest
        check $?

        # go idiomatic linter
        go install golang.org/x/lint/golint@latest
        check $?
    fi
}

install_other_go_packages() {
    if hash go 2>/dev/null; then
        # hey is a tiny program that sends some load to a web application.
        go install github.com/rakyll/hey@latest
        check $?
    fi
}

cleanup_go_binaries() {
    [ -d "${GOPATH}/bin" ] && rm -rf "$GOPATH/bin"
    [ -d "${GOPATH}/pkg" ] && rm -rf "$GOPATH/pkg"
}

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

while true; do
    PS3="Choose an option: "
    options=("Install Common Go Packages Globally" "Install Other Go Packages Globally" "Cleanup Go Binaries" "Quit")

    select opt in "${options[@]}"; do
        case $REPLY in
            1)
                install_common_go_packages
                hr
                break
                ;;
            2)
                install_other_go_packages
                hr
                break
                ;;
            3)
                cleanup_go_binaries
                hr
                break
                ;;
            4) break 2 ;;
            *) echo "Invalid option '$opt'" >&2 ;;
        esac
    done
done
