#!/usr/bin/env bash

type pass >/dev/null 2>/dev/null || exit 1
type sk >/dev/null 2>/dev/null || exit 1

usage() {
    echo "Usage:"
    echo "    $0 --help:"
    echo "        Show this help message"
    echo "    $0 --copy:"
    echo "        Copy password after selection"
    echo "    $0 --view:"
    echo "        View password after selection"
    echo "    $0 --edit"
    echo "        Edit password after selection"
    echo "    $0 [args]"
    echo "        Execute arbitrary [args] pass command"
    echo
    echo " e.g: $0 --copy"
    exit "$1"
}

do_pass() {
    local dir passfile
    dir=$(pwd)
    cd "${PASSWORD_STORE_DIR:-${HOME}/.password-store}" || exit
    passfile=$(tree -Ffi | grep '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | sk)
    cd "$dir" || exit
    if [ -n "$passfile" ]; then
        case "$1" in
            --copy | -c)
                pass --clip "${passfile}"
                ;;
            --view | -v)
                pass "${passfile}"
                ;;
            --edit | -e)
                pass edit "${passfile}"
                ;;
            *) ;;
        esac
    fi
}

nargs=$#
cmd=${1-p}
case $cmd in
    --copy | -c)
        [ "$nargs" -eq 1 ] || usage 1
        do_pass "$cmd"
        ;;
    --view | -v)
        [ "$nargs" -eq 1 ] || usage 1
        do_pass "$cmd"
        ;;
    --edit | -e)
        [ "$nargs" -eq 1 ] || usage 1
        do_pass "$cmd"
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        pass "$@"
        ;;
esac
exit 0
