#!/usr/bin/env bash

type pass >/dev/null 2>/dev/null || exit 1
type sk >/dev/null 2>/dev/null || exit 1

usage() {
    echo "Usage:"
    echo "    $0 help | h:"
    echo "        Show this help message"
    echo "    $0 copy | c:"
    echo "        Copy password after selection"
    echo "    $0 view | v:"
    echo "        View password after selection"
    echo "    $0 edit | e"
    echo "        Edit password after selection"
    echo
    echo " e.g: $0 copy"
    exit "$1"
}

do_pass() {
    local dir passfile
    dir=$(pwd)
    cd "${PASSWORD_STORE_DIR:-${HOME}/.password-store}" || exit
    passfile=$(tree -Ffi | grep '.gpg' | sed 's/.gpg$//g' | sed 's/^..//' | sk)
    cd "$dir" || exit
    if [ -n "$passfile" ]; then
        case "$1" in
            copy | c)
                pass --clip "${passfile}"
                ;;
            view | v)
                pass "${passfile}"
                ;;
            edit | e)
                pass edit "${passfile}"
                ;;
            *) ;;
        esac
    fi
}

nargs=$#
cmd=${1-p}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    copy | c)
        [ "$nargs" -gt 1 ] && usage 1
        do_pass "$cmd"
        ;;
    view | v)
        [ "$nargs" -gt 1 ] && usage 1
        do_pass "$cmd"
        ;;
    edit | e)
        [ "$nargs" -gt 1 ] && usage 1
        do_pass "$cmd"
        ;;
    help | h)
        [ "$nargs" -gt 1 ] && usage 1
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
