#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

. "$HOME/.config/shell/common.sh"

create_c_project_gcc() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Private/Projects/c/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Private/Projects/c/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/c_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .editorconfig to $PROJECT_PATH..."
        cp "$HOME/.editorconfig" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clang-format to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-format" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying CMakeLists.txt to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/CMakeLists.gcc.txt" "$PROJECT_PATH/CMakeLists.txt"
        check $?

        if [ -f /etc/fedora-release ]; then
            echo ">>> Copying compile_flags.txt (fedora) to $PROJECT_PATH..."
            cp "$DOTFILES_DIR/Misc/compile_flags.gcc.fedora.txt" "$PROJECT_PATH/compile_flags.txt"
            check $?
        elif [ ! -f /etc/debian_version ]; then
            echo ">>> Copying compile_flags.txt (debian) to $PROJECT_PATH..."
            cp "$DOTFILES_DIR/Misc/compile_flags.gcc.debian.txt" "$PROJECT_PATH/compile_flags.txt"
            check $?
        else
            echo ">>> Unknown OS (only fedora and debian are supported)..."
        fi

        echo ">>> Initializing 'git' in $PROJECT_PATH..."
        cd "$PROJECT_PATH" && check $?
        git init && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

create_cpp_project_clang() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Private/Projects/cpp/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Private/Projects/cpp/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/cpp_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .editorconfig to $PROJECT_PATH..."
        cp "$HOME/.editorconfig" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clang-format to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-format" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying CMakeLists.txt to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/CMakeLists.clang.txt" "$PROJECT_PATH/CMakeLists.txt"
        check $?

        echo ">>> Copying compile_flags.txt to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/compile_flags.clang.txt" "$PROJECT_PATH/compile_flags.txt"
        check $?

        echo ">>> Copying .clang-tidy to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-tidy" "$PROJECT_PATH/"
        check $?

        echo ">>> Initializing 'git' in $PROJECT_PATH..."
        cd "$PROJECT_PATH" && check $?
        git init && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

create_cpp_project_gcc() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Private/Projects/cpp/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Private/Projects/cpp/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/cpp_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .editorconfig to $PROJECT_PATH..."
        cp "$HOME/.editorconfig" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clang-format to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-format" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying CMakeLists.txt to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/CMakeLists.g++.txt" "$PROJECT_PATH/CMakeLists.txt"
        check $?

        if [ -f /etc/fedora-release ]; then
            echo ">>> Copying compile_flags.txt (fedora) to $PROJECT_PATH..."
            cp "$DOTFILES_DIR/Misc/compile_flags.g++.fedora.txt" "$PROJECT_PATH/compile_flags.txt"
            check $?
        elif [ ! -f /etc/debian_version ]; then
            echo ">>> Copying compile_flags.txt (debian) to $PROJECT_PATH..."
            cp "$DOTFILES_DIR/Misc/compile_flags.g++.debian.txt" "$PROJECT_PATH/compile_flags.txt"
            check $?
        else
            echo ">>> Unknown OS (only fedora and debian are supported)..."
        fi

        echo ">>> Copying .clang-tidy to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-tidy" "$PROJECT_PATH/"
        check $?

        echo ">>> Initializing 'git' in $PROJECT_PATH..."
        cd "$PROJECT_PATH" && check $?
        git init && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

create_rust_project() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Private/Projects/rust/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Private/Projects/rust/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/rust_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .editorconfig to $PROJECT_PATH..."
        cp "$HOME/.editorconfig" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .rustfmt.toml to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.rustfmt.toml" "$PROJECT_PATH/"
        check $?

        cd "$PROJECT_PATH" && check $?

        echo ">>> Initializing 'git' in $PROJECT_PATH..."
        git init && check $?

        echo ">>> Creating 'app' in $PROJECT_PATH..."
        cargo new --bin app && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

create_sfml_project() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Private/Projects/games/sfml/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Private/Projects/games/sfml/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/sfml_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .editorconfig to $PROJECT_PATH..."
        cp "$HOME/.editorconfig" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clang-format to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-format" "$PROJECT_PATH/"
        check $?

        echo ">>> Initializing 'git' in $PROJECT_PATH..."
        cd "$PROJECT_PATH" && check $?
        git init && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

while true; do
    PS3="Choose an option: "
    options=("Create C Project (gcc)" "Create C++ Project (clang)" "Create C++ Project (gcc)" "Create Rust Project" "Create SFML Project" "Quit")

    select opt in "${options[@]}"; do
        case $REPLY in
            1)
                create_c_project_gcc
                hr
                break
                ;;
            2)
                create_cpp_project_clang
                hr
                break
                ;;
            3)
                create_cpp_project_gcc
                hr
                break
                ;;
            4)
                create_rust_project
                hr
                break
                ;;
            5)
                create_sfml_project
                hr
                break
                ;;
            6) break 2 ;;
            *) echo "Invalid option '$opt'" >&2 ;;
        esac
    done
done
