#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 install:"
    echo "        Install rust & cargo-nextest"
    echo "    $0 update:"
    echo "        Update rust & cargo-nextest"
    echo "    $0 package [show|update]:"
    echo "        Show or update global packages installed with cargo"
    echo "    $0 cargo [arbitrary cargo command]:"
    echo "        Run arbitrary cargo command"
    echo
    echo " e.g: $0 package show"
    exit "$1"
}

install_cargo_nextest() {
    curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C "${CARGO_HOME:-~/.cargo}"/bin
    test $? -eq 0 || usage 1
}

install_rust() {
    if hash rustup 2>/dev/null; then
        echo "Rust is already installed, exiting..."
        usage 1
    fi

    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    test $? -eq 0 || usage 1

    rustup component add rust-src rust-analysis rust-analyzer
    test $? -eq 0 || usage 1
}

update_rust() {
    if hash rustup 2>/dev/null; then
        rustup self update
        test $? -eq 0 || usage 1

        rustup update
        test $? -eq 0 || usage 1
    fi
}

show_global_packages() {
    if hash cargo 2>/dev/null; then
        echo "Global Packages Installed:"
        cargo install-update -al
        test $? -eq 0 || usage 1

        echo "Run the following to update:
        $ cargo install-update -a                # Update all installed packages.
        $ cargo install-update crate1 crate2 ... # check for newer versions and update selected packages, will not install new packages."
    fi
}

update_global_packages() {
    if hash cargo 2>/dev/null; then
        cargo install-update -a
        test $? -eq 0 || usage 1
    fi
}

do_package() {
    case $1 in
        show)
            show_global_packages
            ;;
        update)
            update_global_packages
            ;;
        *)
            usage 1
            ;;
    esac
}

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    install)
        [ "$nargs" -eq 1 ] || usage 1
        install_rust
        install_cargo_nextest
        ;;
    update)
        [ "$nargs" -eq 1 ] || usage 1
        update_rust
        install_cargo_nextest
        ;;
    package)
        [ "$nargs" -eq 2 ] || usage 1
        do_package "$@"
        ;;
    cargo)
        [ "$nargs" -lt 2 ] && usage 1
        if hash cargo 2>/dev/null; then
            cargo "$@"
        else
            echo "cargo not installed, exiting..."
            exit 1
        fi
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
