#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace

if [[ -z "${BASH_VERSION}" ]]; then
    echo "Error: This script requires Bash to run." >&2
    exit 1
fi

SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_NAME
cd "$(dirname "$0")" || exit 1

# shellcheck source=/dev/null
source "$HOME/.config/shell/lib/functions.sh"

usage() {
    echo "Usage:"
    echo "    $SCRIPT_NAME help:"
    echo "        Show this help message"
    echo "    $SCRIPT_NAME system:"
    echo "        Update OS (debian, opensuse or fedora) & Flatpak"
    echo "    $SCRIPT_NAME dotfiles:"
    echo "        Update personal dotfiles (ask to pull from remote and then syncs on local)"
    echo "    $SCRIPT_NAME psd:"
    echo "        Update psd (profile-sync-daemon) from source (will update to latest psd from git repository)"
    echo "    $SCRIPT_NAME emacs:"
    echo "        Update emacs from source (will update to latest emacs from git repository)"
    echo "    $SCRIPT_NAME stylua:"
    echo "        Update StyLua from binary source"
    echo "    $SCRIPT_NAME xremap:"
    echo "        Update xreamp from binary source"
    echo "    $SCRIPT_NAME vicinae:"
    echo "        Update Vicinae from source"
    echo "    $SCRIPT_NAME harper:"
    echo "        Update harper from binary source"
    echo
    echo " e.g: $SCRIPT_NAME system"
    exit "$1"
}

debian_update() {
    sudo extrepo update
    test $? -eq 0 || usage 1

    sudo apt update -y
    test $? -eq 0 || usage 1

    sudo apt upgrade -y
    test $? -eq 0 || usage 1

    sudo apt full-upgrade
    test $? -eq 0 || usage 1

    sudo apt autoremove
    test $? -eq 0 || usage 1

    sudo apt autoclean
    test $? -eq 0 || usage 1

    sudo flatpak update -y
    test $? -eq 0 || usage 1
}

opensuse_update() {
    # For Leap
    # sudo zypper ref && sudo zypper update
    # test $? -eq 0 || usage 1

    # For Tumbleweed
    sudo zypper ref && sudo zypper dup
    test $? -eq 0 || usage 1

    # Flatpak
    flatpak update --user -y
    test $? -eq 0 || usage 1
}

fedora_update() {
    sudo dnf -y --refresh upgrade
    test $? -eq 0 || usage 1

    sudo dnf -y distro-sync
    test $? -eq 0 || usage 1

    sudo dnf -y autoremove
    test $? -eq 0 || usage 1

    flatpak update --user -y
    test $? -eq 0 || usage 1
}

system_update() {
    local OS
    [[ -f /etc/debian_version ]] && OS=Debian
    [[ -f /etc/products.d/openSUSE.prod ]] && OS=OpenSuse
    [[ -f /etc/fedora-release ]] && OS=Fedora

    [[ $OS == Debian ]] && (hash apt 2> /dev/null || usage 1)
    [[ $OS == OpenSuse ]] && (hash zypper 2> /dev/null || usage 1)
    [[ $OS == Fedora ]] && (hash dnf 2> /dev/null || usage 1)

    [[ $OS == Debian ]] && debian_update
    [[ $OS == OpenSuse ]] && opensuse_update
    [[ $OS == Fedora ]] && fedora_update
}

dotfiles_update() {
    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    test $? -eq 0 || usage 1

    if [ -d "$DOTFILES_DIR" ]; then
        git -C "${DOTFILES_DIR}" status
        test $? -eq 0 || usage 1

        if ask "Do you want to pull from remote?"; then
            git -C "${DOTFILES_DIR}" pull
            test $? -eq 0 || usage 1
        fi

        if [ -f "${DOTFILES_DIR}/make.sh" ]; then
            "${DOTFILES_DIR}/make.sh"
            test $? -eq 0 || usage 1
        fi
    fi
}

psd_update() {
    # Dependencies
    sudo dnf install -y coreutils findutils glib2 kmod rsync systemd

    # Set branch to use
    local PSD_BRANCH
    PSD_BRANCH=master

    # Prepare git repo
    [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
    if [ ! -d "$HOME"/Workspace/Software/profile-sync-daemon ]; then
        git clone --depth 1 --branch "$PSD_BRANCH" git@github.com:graysky2/profile-sync-daemon.git \
            "$HOME"/Workspace/Software/profile-sync-daemon
        pushd "$HOME"/Workspace/Software/profile-sync-daemon
    else
        pushd "$HOME"/Workspace/Software/profile-sync-daemon

        # Stop the service
        systemctl is-active psd.service && systemctl --user stop psd.service

        # Fetch update
        sudo make uninstall
        make clean && make distclean
        git reset --hard HEAD
        sudo git clean -dfx
        git fetch && git pull
    fi

    # Setup git branch
    local BRANCH
    BRANCH=$(git branch --show-current)
    [[ "$BRANCH" != "$PSD_BRANCH" ]] && echo "PSD unexpected branch, expecting $PSD_BRANCH, got $BRANCH" && usage 1

    # Install
    make -j"$(nproc --ignore=2)"
    sudo make install

    popd

    #
    # All the below should have been done on post_install script!
    #
    # # Copy brave profile
    # if [ -f /usr/share/psd/contrib/brave ]; then
    #     sudo cp /usr/share/psd/contrib/brave /usr/share/psd/browsers
    # elif [ -f "$HOME"/Workspace/Public/dotfiles/Common/psd/brave ]; then
    #     sudo cp "$HOME"/Workspace/Public/dotfiles/Common/psd/brave /usr/share/psd/browsers
    # fi
    #
    # # PSD: Needs sudo permissions for overlay-fs - needs a logout :(
    # echo 'jvillasante ALL=(ALL) NOPASSWD: /usr/bin/psd-overlay-helper' | sudo EDITOR='tee -a' visudo
    #
    # # PSD: Enable and Start the Daemon
    # systemctl --user enable --now psd.service && systemctl --user start psd.service
}

emacs_update() {
    # Preconditions
    ! hash emacs 2> /dev/null && echo "emacs not installed, exiting..." && usage 1
    [[ ! -d "$HOME"/Workspace/Software ]] &&
        echo "$HOME/Workspace/Software does not exists, exiting..." && usage 1
    [[ ! -d "$HOME"/Workspace/Software/emacs ]] &&
        echo "$HOME/Workspace/Software/emacs does not exists, exiting..." && usage 1

    # Stop the service
    emacsclient --eval '(progn (setq confirm-kill-emacs nil) (save-buffers-kill-emacs))'
    systemctl --user stop emacs.service

    # Prepare git repo
    pushd "$HOME"/Workspace/Software/emacs || usage 1
    sudo make uninstall
    make clean && make distclean
    git reset --hard HEAD
    sudo git clean -dfx
    git fetch && git pull

    # Set branch to use
    local EMACS_BRANCH
    EMACS_BRANCH=emacs-30

    # Setup git branch
    local BRANCH
    BRANCH=$(git branch --show-current)
    [[ "$BRANCH" != "$EMACS_BRANCH" ]] && echo "Found $BRANCH while expecting $EMACS_BRANCH, exiting..." && usage 1

    # Build and install
    # Pure GTK: --with-x-toolkit=no --with-pgtk
    # Lucid: --with-x-toolkit=lucid --with-cairo --with-xft
    ./autogen.sh
    ./configure \
          --prefix=/usr/local \
          --without-compress-install \
          --disable-gc-mark-trace \
          --with-x-toolkit=lucid --with-cairo --with-xft \
          --with-native-compilation=aot \
          --with-tree-sitter \
          CFLAGS="-O2 -mtune=native -march=native -pipe -fomit-frame-pointer"
    make -j"$(nproc --ignore=2)" NATIVE_FULL_AOT=1
    sudo make install

    # Cleanup
    popd || usage 1

    # Update packages
    if ask "Emacs has been installed, do you want to update packages now?"; then
        local DOTFILES_DIR
        DOTFILES_DIR="$(find_dotfiles)"
        test $? -eq 0 || usage 1

        # Clean up some trash
        [[ ! -d "$DOTFILES_DIR"/Common/emacs/emacs.d ]] &&
            echo "Emacs personal configuration not found, exiting..." && usage 1
        [[ -d "$DOTFILES_DIR"/Common/emacs/emacs.d/var/eln-cache ]] &&
            rm -rf "$DOTFILES_DIR"/Common/emacs/emacs.d/var/eln-cache
        [[ -d "$DOTFILES_DIR"/Common/emacs/emacs.d/var/elpa ]] &&
            rm -rf "$DOTFILES_DIR"/Common/emacs/emacs.d/var/elpa
        [[ -d "$DOTFILES_DIR"/Common/emacs/emacs.d/var/tree-sitter ]] &&
            rm -rf "$DOTFILES_DIR"/Common/emacs/emacs.d/var/tree-sitter

        # Launch emacs
        /usr/local/bin/emacs --init-directory="$DOTFILES_DIR"/Common/emacs/emacs.d
    fi

    if ask "Emacs packages updated, do you want to start the daemon as a systemd service now?"; then
        systemctl --user daemon-reload
        test $? -eq 0 || usage 1

        systemctl --user enable emacs.service
        test $? -eq 0 || usage 1

        systemctl --user stop emacs.service
        systemctl --user start emacs.service
        test $? -eq 0 || usage 1

        sleep 1 && systemctl --user status emacs.service
        test $? -eq 0 || usage 1
    fi
}

stylua_update() {
    ! hash stylua 2> /dev/null && echo "stylua not installed, exiting..." && usage 1
    [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
    [ ! -d "$HOME"/Workspace/Software/stylua ] && mkdir -p "$HOME"/Workspace/Software/stylua
    [ -d "$HOME"/Workspace/Software/stylua ] && rm -rf "$HOME"/Workspace/Software/stylua/*

    pushd "$HOME"/Workspace/Software/stylua || {
        echo "Can't cd into $HOME/Workspace/Software/stylua"
        usage 1
    }

    # Get the latest
    STYLUA_VERSION=v2.3.1
    STYLUA_RELEASE=stylua-linux-x86_64.zip
    curl -LJO https://github.com/JohnnyMorganz/StyLua/releases/download/"$STYLUA_VERSION"/"$STYLUA_RELEASE"
    atool --extract --explain "$STYLUA_RELEASE"
    sudo cp -f stylua /usr/local/bin/

    popd || {
        echo "Can't pop directory"
        usage 1
    }
}

xremap_update() {
    ! hash xremap 2> /dev/null && echo "xremap not installed, exiting..." && usage 1
    [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
    [ ! -d "$HOME"/Workspace/Software/xremap ] && mkdir -p "$HOME"/Workspace/Software/xremap
    [ -d "$HOME"/Workspace/Software/xremap ] && rm -rf "$HOME"/Workspace/Software/xremap/*

    pushd "$HOME"/Workspace/Software/xremap || {
        echo "Can't cd into $HOME/Workspace/Software/xremap"
        usage 1
    }

    # Get the latest
    XREMAP_VERSION=v0.14.3
    XREMAP_RELEASE=xremap-linux-x86_64-kde.zip
    if is_desktop_environment "Gnome"; then
        XREMAP_RELEASE=xremap-linux-x86_64-gnome.zip
    fi

    curl -LJO https://github.com/k0kubun/xremap/releases/download/"$XREMAP_VERSION"/"$XREMAP_RELEASE"
    atool --extract --explain "$XREMAP_RELEASE"
    sudo cp -f xremap /usr/local/bin/

    popd || {
        echo "Can't pop directory"
        usage 1
    }

    # Restart the daemon
    systemctl --user daemon-reload
    systemctl --user restart xremap.service
}

vicinae_update() {
    ! hash vicinae 2> /dev/null && echo "vicinae not installed, exiting..." && usage 1

    # Install
    curl -fsSL https://vicinae.com/install.sh | bash

    # Restart the daemon
    systemctl --user daemon-reload
    systemctl --user restart vicinae
}

harper_update() {
    # Is it already installed?
    # ! hash harper-cli 2> /dev/null && echo "Harper not installing, exiting" && usage 1
    # ! hash harper-ls 2> /dev/null && echo "Harper not installing, exiting" && usage 1
    [ ! -d "$HOME"/Workspace/Software ] && mkdir -p "$HOME"/Workspace/Software
    [ ! -d "$HOME"/Workspace/Software/harper ] && mkdir -p "$HOME"/Workspace/Software/harper
    [ -d "$HOME"/Workspace/Software/harper ] && rm -rf "$HOME"/Workspace/Software/harper/*

    pushd "$HOME"/Workspace/Software/harper || {
        echo "Can't cd into $HOME/Workspace/Software/harper"
        usage 1
    }

    # get the latest
    HARPER_VERSION=v0.70.0
    HARPER_CLI_RELEASE=harper-cli-x86_64-unknown-linux-gnu.tar.gz
    HARPER_LS_RELEASE=harper-ls-x86_64-unknown-linux-gnu.tar.gz

    curl -LJO https://github.com/Automattic/harper/releases/download/"$HARPER_VERSION"/"$HARPER_CLI_RELEASE"
    atool --extract --explain "$HARPER_CLI_RELEASE"
    sudo cp -f harper-cli /usr/local/bin/

    curl -LJO https://github.com/Automattic/harper/releases/download/"$HARPER_VERSION"/"$HARPER_LS_RELEASE"
    atool --extract --explain "$HARPER_LS_RELEASE"
    sudo cp -f harper-ls /usr/local/bin/

    popd || {
        echo "Can't cd to previous directory"
        usage 1
    }
}

main() {
    nargs=$#
    cmd=${1-}
    rc=0
    if [ "$#" -gt 0 ]; then shift; fi
    case $cmd in
        system)
            [[ "$nargs" -eq 1 ]] || usage 1
            system_update
            ;;
        dotfiles)
            [ "$nargs" -eq 1 ] || usage 1
            dotfiles_update
            ;;
        psd)
            [[ "$nargs" -eq 1 ]] || usage 1
            psd_update
            ;;
        emacs)
            [[ "$nargs" -eq 1 ]] || usage 1
            emacs_update
            ;;
        stylua)
            [[ "$nargs" -eq 1 ]] || usage 1
            stylua_update
            ;;
        xremap)
            [[ "$nargs" -eq 1 ]] || usage 1
            xremap_update
            ;;
        vicinae)
            [[ "$nargs" -eq 1 ]] || usage 1
            vicinae_update
            ;;
        harper)
            [[ "$nargs" -eq 1 ]] || usage 1
            harper_update
            ;;
        help | --help | -h)
            usage 0
            ;;
        *)
            usage 1
            ;;
    esac
    return $rc
}

main "$@"
