#!/usr/bin/env bash

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 system:"
    echo "        Update OS (debian or fedora)"
    echo
    echo " e.g: $0 system"
    exit "$1"
}

debian_update() {
    sudo apt update -y
    test $? -eq 0 || usage 1

    sudo apt upgrade -y
    test $? -eq 0 || usage 1

    sudo apt full-upgrade
    test $? -eq 0 || usage 1

    sudo apt autoremove
    test $? -eq 0 || usage 1

    sudo flatpak update -y
    test $? -eq 0 || usage 1
}

fedora_update() {
    sudo dnf -y --refresh upgrade
    test $? -eq 0 || usage 1

    sudo dnf -y distro-sync
    test $? -eq 0 || usage 1

    sudo dnf -y autoremove
    test $? -eq 0 || usage 1

    sudo flatpak update -y
    test $? -eq 0 || usage 1
}

system_update() {
    local OS
    [[ -f /etc/debian_version ]] && OS=Debian
    [[ -f /etc/fedora-release ]] && OS=Fedora

    [[ $OS == Debian ]] && (hash apt 2>/dev/null || usage 1)
    [[ $OS == Fedora ]] && (hash dnf 2>/dev/null || usage 1)

    [[ $OS == Debian ]] && debian_update
    [[ $OS == Fedora ]] && fedora_update
}

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    system)
        [[ "$nargs" -eq 1 ]] || usage 1
        system_update
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
