#!/usr/bin/env bash

#
# Encryption:
#   Encrypts file or directory using gpg symmetric or asymmetric encryption.
#   The output is on the form "*.tar.gz.gpg" (symmetric) or "*.tar.gz.asc" (asymmetric).
#   Files are moved into a directory of the same basename first.
#
# Decryption:
#   Decrypts file using gpg (previously encrypted with `encrypt`).
#   Expects and argument with the form "*.tar.gz.gpg" (symmetric) or "*.tar.gz.asc (asymmetric)"
#

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace

usage() {
    echo "Usage:"
    echo "    $0 help:"
    echo "        Show this help message"
    echo "    $0 -e [-s | -a] [file | directory]:"
    echo "        -e: encrypt the given *file* or *directory*"
    echo "        -s: symmetric gpg encryption"
    echo "        -a: asymmetric gpg encryption"
    echo "    $0 -d [filename.tar.gz.gpg | filename.tar.gz.asc]:"
    echo "        -d: decrypt the given file"
    echo "        *.tar.gz.gpg: assumes file was encrypted with symmetric gpg encryption"
    echo "        *.tar.gz.asc: assumes file was encrypted with asymmetric gpg encryption"
    echo
    echo " e.g: $0 -e -s /path/to/file/or/directory"
    echo " e.g: $0 -d /path/to/file/or/directory.tar.gz.gpg"
    exit "$1"
}

encrypt() {
    if [ -z "$1" ] || [ "$1" != "-s" ] && [ "$1" != "-a" ]; then
        echo "Illegal arguments ($1 must exist and be either '-s (symmetric)' or '-a (asymmetric)')"
        echo "  Usage: ./crypt -e [-s | -a] [file | directory]"
        exit 1
    fi

    if [ -z "$2" ] || [ ! -f "$2" ] && [ ! -d "$2" ]; then
        echo "Illegal arguments ($2 must exist and be either a file or directory)"
        echo "  Usage: ./crypt -e [-s | -a] [file | directory]"
        exit 1
    fi

    local target
    target=$(realpath "$2")
    local parent_dir
    parent_dir=$(dirname "$target")
    local base_name
    base_name=$(basename "$target")

    if [[ -f "$target" ]]; then
        base_name="${base_name%.*}"
        mkdir -p "$parent_dir/$base_name"
        mv "$target" "$parent_dir/$base_name/"
        target="$parent_dir/$base_name"
    fi

    local tar_file="$parent_dir/$base_name.tar.gz"
    tar czf "$tar_file" -C "$parent_dir" "$(basename "$target")"

    if [ "$1" = "-s" ]; then
        gpg --symmetric --cipher-algo AES256 -o "$tar_file.gpg" "$tar_file"
        echo "Encrypted $2 to $tar_file.gpg (symmetric)"
    elif [ "$1" = "-a" ]; then
        gpg --encrypt --sign --armor -r jvillasantegomez@gmail.com -o "$tar_file.asc" "$tar_file"
        echo "Encrypted $2 to $tar_file.asc (asymmetric)"
    else
        echo "Invalid argument $2, exiting..."
        exit 1
    fi

    rm -f "$tar_file"

    # TODO: Add a flag for output directory
    # TODO: Remove original (put this behind a flag)
    # rm -rf "$target"
}

do_decrypt() {
    local DIR
    DIR=$(dirname "$1")

    local filename
    filename=$(basename "$1")

    local p
    case "$filename" in
        *.tar.gz.gpg) p="$DIR/${filename%.tar.gz.gpg}" ;;
        *.tar.gz.asc) p="$DIR/${filename%.tar.gz.asc}" ;;
        *)             p="$DIR/${filename%.*}" ;;
    esac

    gpg --decrypt -o "$p.tar.gz" "$1" > /dev/null 2> /dev/null
    tar xzf "$p.tar.gz" --warning=no-timestamp -C "$DIR"
    rm -f "$p.tar.gz"

    # TODO: Remove original (put this behind a flag)
    # rm -rf "$1"

    echo "Decrypted $1 to $p ($2)"
}

decrypt() {
    if [ -z "$1" ] || [ ! -f "$1" ]; then
        echo "Illegal arguments ($1 must exist and be a file)"
        echo "  Usage: ./crypt -d [filename.tar.gz.gpg (symmetric) | filename.tar.gz.asc (asymmetric)]"
        exit 1
    fi

    echo "Decrypting $1..."
    case "$1" in
        *.tar.gz.asc)
            do_decrypt "$1" "asymmetric" ;;
        *.tar.gz.gpg)
            do_decrypt "$1" "symmetric" ;;
        *)
            echo "Illegal arguments ($1 must exist and be a file)"
            echo "  Usage: ./crypt -d [filename.tar.gz.gpg (symmetric) | filename.tar.gz.asc (asymmetric)]"
            exit 1 ;;
    esac
}

nargs=$#
cmd=${1-}
rc=0
if [ "$#" -gt 0 ]; then shift; fi
case $cmd in
    -e)
        [ "$nargs" -eq 3 ] || usage 1
        time (encrypt "$@")
        ;;
    -d)
        [ "$nargs" -eq 2 ] || usage 1
        time (decrypt "$@")
        ;;
    help | --help | -h)
        usage 0
        ;;
    *)
        usage 1
        ;;
esac
exit $rc
