#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace

if [[ -z "${BASH_VERSION}" ]]; then
    echo "Error: This script requires Bash to run." >&2
    exit 1
fi

SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_NAME
cd "$(dirname "$0")" || exit 1

# shellcheck source=/dev/null
source "$HOME/.config/shell/lib/functions.sh"

# source everything in lib
for f in "$HOME"/.config/shell/lib/*; do
    # shellcheck source=/dev/null
    source "$f" || exit 1
done

usage() {
    echo "Usage:"
    echo "    $SCRIPT_NAME help:"
    echo "        Show this help message"
    echo "    $SCRIPT_NAME c:"
    echo "        Create C Project (gcc)"
    echo "    $SCRIPT_NAME cpp:"
    echo "        Create C++ Project (gcc)"
    echo "    $SCRIPT_NAME rust:"
    echo "        Create Rust Project"
    echo "    $SCRIPT_NAME sfml:"
    echo "        Create SFML Project"
    echo
    echo " e.g: $SCRIPT_NAME cpp"
    exit "$1"
}

create_c_project() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Scratch/c/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Scratch/c/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/c_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clangd to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clangd" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clang-format to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-format" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying CMakeLists.txt to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/CMakeLists.gcc.txt" "$PROJECT_PATH/CMakeLists.txt"
        check $?

        # if [ -f /etc/fedora-release ]; then
        #     echo ">>> Copying compile_flags.txt (fedora) to $PROJECT_PATH..."
        #     cp "$DOTFILES_DIR/Misc/compile_flags.gcc.fedora.txt" "$PROJECT_PATH/compile_flags.txt"
        #     check $?
        # elif [ -f /etc/debian_version ]; then
        #     echo ">>> Copying compile_flags.txt (debian) to $PROJECT_PATH..."
        #     cp "$DOTFILES_DIR/Misc/compile_flags.gcc.debian.txt" "$PROJECT_PATH/compile_flags.txt"
        #     check $?
        # elif [ -f /etc/products.d/openSUSE.prod ]; then
        #     echo ">>> Copying compile_flags.txt (suse) to $PROJECT_PATH..."
        #     cp "$DOTFILES_DIR/Misc/compile_flags.gcc.suse.txt" "$PROJECT_PATH/compile_flags.txt"
        #     check $?
        # else
        #     echo ">>> Unknown OS (only fedora, suse and debian are supported)..."
        # fi

        echo ">>> Initializing 'git' in $PROJECT_PATH..."
        cd "$PROJECT_PATH" && check $?
        git init && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

create_cpp_project() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Scratch/cpp/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Scratch/cpp/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/cpp_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clangd to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clangd" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clang-format to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-format" "$PROJECT_PATH/"
        check $?

        # if [ -f /etc/fedora-release ]; then
        #     echo ">>> Copying compile_flags.txt (fedora) to $PROJECT_PATH..."
        #     cp "$DOTFILES_DIR/Misc/compile_flags.gcc.fedora.txt" "$PROJECT_PATH/compile_flags.txt"
        #     check $?
        # elif [ -f /etc/debian_version ]; then
        #     echo ">>> Copying compile_flags.txt (debian) to $PROJECT_PATH..."
        #     cp "$DOTFILES_DIR/Misc/compile_flags.gcc.debian.txt" "$PROJECT_PATH/compile_flags.txt"
        #     check $?
        # elif [ -f /etc/products.d/openSUSE.prod ]; then
        #     echo ">>> Copying compile_flags.txt (suse) to $PROJECT_PATH..."
        #     cp "$DOTFILES_DIR/Misc/compile_flags.gcc.suse.txt" "$PROJECT_PATH/compile_flags.txt"
        #     check $?
        # else
        #     echo ">>> Unknown OS (only fedora, suse and debian are supported)..."
        # fi

        echo ">>> Copying .clang-tidy to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-tidy" "$PROJECT_PATH/"
        check $?

        echo ">>> Initializing $PROJECT_PATH..."
        cd "$PROJECT_PATH" && check $?
        git init && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

create_rust_project() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Scratch/rust/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Scratch/rust/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/rust_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .rustfmt.toml to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.rustfmt.toml" "$PROJECT_PATH/"
        check $?

        cd "$PROJECT_PATH" && check $?

        echo ">>> Initializing 'git' in $PROJECT_PATH..."
        git init && check $?

        echo ">>> Creating 'app' in $PROJECT_PATH..."
        cargo new --bin app && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

create_sfml_project() {
    read -r -p "Enter project name: " PROJECT_NAME
    read -r -p "Enter project path (default to ~/Workspace/Scratch/games/sfml/): " PROJECT_PATH
    if [ -z "$PROJECT_PATH" ]; then
        PROJECT_PATH="$HOME/Workspace/Scratch/games/sfml/$PROJECT_NAME"
    else
        if [ ! -d "$PROJECT_PATH" ]; then
            echo ">>> $PROJECT_PATH does not exists, exiting..."
            exit 1
        fi
        PROJECT_PATH="$PROJECT_PATH/$PROJECT_NAME"
    fi

    local DOTFILES_DIR
    DOTFILES_DIR="$(find_dotfiles)"
    if [ ! -d "$PROJECT_PATH" ]; then
        echo ">>> $PROJECT_PATH does not exists, creating it..."
        mkdir -p "$PROJECT_PATH"
        check $?

        echo ">>> Copying project template to $PROJECT_PATH..."
        cp -a "$DOTFILES_DIR/Misc/templates/sfml_project_template/." "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clangd to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clangd" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clang-format to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-format" "$PROJECT_PATH/"
        check $?

        echo ">>> Copying .clang-tidy to $PROJECT_PATH..."
        cp "$DOTFILES_DIR/Misc/.clang-tidy" "$PROJECT_PATH/"
        check $?

        echo ">>> Initializing 'git' in $PROJECT_PATH..."
        cd "$PROJECT_PATH" && check $?
        git init && check $?
    else
        echo ">>> $PROJECT_PATH already exists."
    fi
}

main() {
    nargs=$#
    cmd=${1-}
    rc=0
    if [ "$#" -gt 0 ]; then shift; fi
    case $cmd in
        c)
            [[ "$nargs" -eq 1 ]] || usage 1
            create_c_project
            ;;
        cpp)
            [ "$nargs" -eq 1 ] || usage 1
            create_cpp_project
            ;;
        rust)
            [[ "$nargs" -eq 1 ]] || usage 1
            create_rust_project
            ;;
        sfml)
            [[ "$nargs" -eq 1 ]] || usage 1
            create_sfml_project
            ;;
        help | --help | -h)
            usage 0
            ;;
        *)
            usage 1
            ;;
    esac
    return $rc
}

main "$@"
