#!/usr/bin/env bash

#
# lists zombie processes
#

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE-0}" == "1" ]] && set -o xtrace
cd "$(dirname "$0")" || exit 1

ps aux | awk '{if ($8=="Z") { print $2 }}'
