#!/usr/bin/env bash

# tty
stty -ixon    # Disable flow control, i.e. ^s "freeze screen" and ^q resume
stty erase ^? # kill ^u intr ^c eof ^d stop ^s
set -o emacs

# term
export TERM=xterm-256color

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# XDG_* should be set
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_LIB_HOME="${XDG_LIB_HOME:-$HOME/.local/lib}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

# Don't put duplicate lines or liens starting with space int he history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable programmable completion features
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# PS1
eval "$(starship init bash)"

# Emacs please
if type emacs > /dev/null 2> /dev/null; then
    export ALTERNATE_EDITOR=""
    export VISUAL="emacsclient -c -a ''"   # $VISUAL opens in GUI and waits
    export EDITOR="$VISUAL"

    function e        { emacsclient -c -a '' --eval "(progn (select-frame-set-input-focus (selected-frame)) (find-file \"$1\"))"; }
    function et       { emacsclient -t -a '' --eval "(progn (find-file \"$1\"))"; }
    function ediff    { emacsclient -c -a '' --eval "(progn (select-frame-set-input-focus (selected-frame)) (ediff-files \"$1\" \"$2\"))"; }
    function edired   { emacsclient -c -a '' --eval "(progn (select-frame-set-input-focus (selected-frame)) (dired \"$1\"))"; }
    function emagit   { emacsclient -c -a '' --eval "(progn (select-frame-set-input-focus (selected-frame)) (magit-status \"$1\"))"; }
    function ekill    { emacsclient --eval '(save-buffers-kill-emacs)'; }
    function estatus  { systemctl --user status emacs.service; }
    function eminimal { emacs --init-directory="$HOME"/Workspace/Public/dotfiles/Common/emacs/minimal/ "$@"; }
fi

# vim
type vim > /dev/null 2>&1 && alias vi=vim
type nvim > /dev/null 2>&1 && alias vim=nvim

# gpg
if type gpg2 > /dev/null 2> /dev/null; then
    # gpg is not gpg2 if installed
    alias gpg='gpg2'
fi
export GPG_TTY=$(tty)
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# ssh
alias ssh="TERM=xterm-256color ssh"
export SSH_KEY_PATH="$HOME/.ssh/dsa_id"

# utils
alias hex="od -Ax -tx1z -v"
alias ls="ls --group-directories-first --color"
alias ll="ls -AlFh --group-directories-first --color"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -I" # IMHO, much better than 'rm -i'
alias tree="tree --dirsfirst -a -I 'node_modules|.git'"
alias ag="ag --hidden --ignore node_modules --ignore .git"
alias reboot='systemctl reboot'
alias poweroff='systemctl poweroff'

# eza (ls replacement)
if type eza > /dev/null 2> /dev/null; then
    alias ls='eza --git --group-directories-first --color=automatic'
    alias ll='eza -agFlh --git --group-directories-first --color=automatic'
fi

# ripgrep
if type rg > /dev/null 2> /dev/null; then
    alias grep='rg -S --color=auto'
fi

# bat
if type bat > /dev/null 2> /dev/null; then
    alias bat='bat --theme ansi'
    # alias cat='bat --theme ansi'
fi

# fd-find
if type fdfind > /dev/null 2> /dev/null; then
    alias fd='fdfind'
fi

# surf: these options are very opinionated, disabling images, javascript, etc.
if type surf > /dev/null 2>&1; then
    alias surf="surf -giKMnps"
fi

# keepassxs : not using this yet
# if flatpak info org.keepassxc.KeePassXC >/dev/null 2>/dev/null; then
#     alias keepassxc="flatpak run org.keepassxc.KeePassXC"
# fi

#
# Mac Stuff
#
if [ "$(uname -s)" = "Darwin" ]; then
    # Toggle hidden files on mac
    alias show_hidden_files='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
    alias hide_hidden_files='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

    # Enable font smoothing
    defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

    # Symlink workspace volume
    if [ ! -d "$HOME/Workspace" ]; then
        ln -nfs /Volumes/Workspace/ ~/Workspace
    fi
fi

#
# Linux Stuff
#
if [ "$(uname -s)" = 'Linux' ]; then
    alias open='xdg-open'

    if [ -f /etc/fedora-release ]; then
        # Known bug with gpg on Fedora
        gpg_pcscd_restart() {
            sudo systemctl restart pcscd
        }
    fi
fi

#
# Execute tmux (alacritty supports this natively)
#
# if [ -x "$(command -v tmux)" ] && [ -n "${DISPLAY}" ] && [ -z "${TMUX}" ] && [ -z "$INSIDE_EMACS" ]; then
#     ( tmux attach || tmux new -s Default > /dev/null 2>&1) && exit 0
# fi

#
# Fuzzy Finder
#
# . "${HOME}/.config/shell/system/skim"
. "${HOME}/.config/shell/system/fzf"
