#!/usr/bin/env bash

# tty
stty -ixon    # Disable flow control, i.e. ^s "freeze screen" and ^q resume
stty erase ^? # kill ^u intr ^c eof ^d stop ^s
set -o emacs

# term
export TERM=xterm-256color

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# XDG_* should be set
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_LIB_HOME="${XDG_LIB_HOME:-$HOME/.local/lib}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

# Don't put duplicate lines or liens starting with space int he history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# PS1
eval "$(starship init bash)"

# Use bash-completion, if available
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] &&
    source /usr/share/bash-completion/bash_completion

# Editor: Emacs please
if type emacs >/dev/null 2>/dev/null; then
    export ALTERNATE_EDITOR=""
    export VISUAL="emacsclient -c -n -a ''" # $VISUAL opens in GUI no wait
    export EDITOR="emacsclient -c -a ''"    # $EDITOR opens in GUI and waits

    alias em="emacsclient -c -a ''"        # opens the GUI
    alias emt="emacsclient -t -a ''"       # used to be "emacs -nw"
    alias semt="sudo emacsclient -t -a ''" # used to be "sudo emacs -nw"

    ediff() { emacsclient -c -a '' --eval "(ediff-files \"$1\" \"$2\")"; }
    edired() { emacsclient -c -a '' --eval "(progn (dired \"$1\"))"; }
    ekill() { emacsclient --eval '(kill-emacs)'; }
fi

# vim
type nvim >/dev/null 2>&1 && alias vim=nvim
type vim >/dev/null 2>&1 && alias vi=vim

# ssh
alias ssh="TERM=xterm-256color ssh"
export SSH_KEY_PATH="$HOME/.ssh/dsa_id"

# utils
alias hex="od -Ax -tx1z -v"
alias ls="ls --group-directories-first --color"
alias ll="ls -AlFh --group-directories-first --color"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -I" # IMHO, much better than 'rm -i'
alias tree="tree --dirsfirst -a -I 'node_modules|.git'"
alias ag="ag --hidden --ignore node_modules --ignore .git"
alias reboot="systemctl reboot"

# atool to extract archives
if type atool >/dev/null 2>/dev/null; then
    +extract() {
        atool --extract --explain "$@"
    }
fi

# exa
if type exa >/dev/null 2>/dev/null; then
    alias ls='exa --git --group-directories-first --color=auto'
    alias ll='exa -agFlh --git --group-directories-first --color=auto'
fi

# ripgrep
if type rg >/dev/null 2>/dev/null; then
    alias grep='rg -S --color=auto'
fi

# bat
if type bat >/dev/null 2>/dev/null; then
    alias bat='bat --theme ansi'
    # alias cat='bat --theme ansi'
fi

# gpg is not gpg2 if installed
if type gpg2 >/dev/null 2>/dev/null; then
    alias gpg='gpg2'
fi

# surf: these options are very opinionated, disabling images, javascript, etc.
if type surf >/dev/null 2>&1; then
    alias surf="surf -giKMnps"
fi

#
# Mac Stuff
#
if [ "$(uname -s)" = "Darwin" ]; then
    # Toggle hidden files on mac
    alias show_hidden_files='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
    alias hide_hidden_files='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

    # Enable font smoothing
    defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

    # Symlink workspace volume
    if [ ! -d "$HOME/Workspace" ]; then
        ln -nfs /Volumes/Workspace/ ~/Workspace
    fi
fi

#
# Linux Stuff
#
if [ "$(uname -s)" = 'Linux' ]; then
    alias open='xdg-open'

    # Known bug with gpg on Fedora
    gpg_pcscd_restart() {
        sudo systemctl restart pcscd
    }
fi

#
# Emacs vterm (https://github.com/akermu/emacs-libvterm)
#
if [ "$INSIDE_EMACS" = 'vterm' ] &&
    [ -n "$EMACS_VTERM_PATH" ] &&
    [ -f "$EMACS_VTERM_PATH/etc/emacs-vterm-bash.sh" ]; then
    source "$EMACS_VTERM_PATH/etc/emacs-vterm-bash.sh"
fi

#
# Fuzzy Finder (https://github.com/lotabout/skim)
#
# source "${HOME}/.config/shell/system/skim"
source "${HOME}/.config/shell/system/fzf"
