(("default" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/Common/emacs/personal")
                  (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/personal/custom.el")))
    ("personal" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/Common/emacs/personal")
                      (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/personal/custom.el")))
    ("minimal" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/Common/emacs/minimal")
                     (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/minimal/custom.el")))
    ("doom" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/.emacs.doom")
                  (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/doom/custom.el")
                  (env . (("DOOMDIR" . "~/Workspace/Public/dotfiles/Common/emacs/doom"))))))
