(
    ;; ("default" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/.emacs.doom")
    ;;                  (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/doom/custom.el")
    ;;                  (env . (("DOOMDIR" . "~/Workspace/Public/dotfiles/Common/emacs/doom")))))
    ("default" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/Common/emacs/personal")
                     (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/personal/custom.el")))
    ("doom" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/.emacs.doom")
                  (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/doom/custom.el")
                  (env . (("DOOMDIR" . "~/Workspace/Public/dotfiles/Common/emacs/doom")))))
    ("crafted" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/.emacs.crafted")
                     (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/crafted/custom.el")
                     (env . (("CRAFTED_EMACS_HOME" . "~/Workspace/Public/dotfiles/Common/emacs/crafted")))))
    ("personal" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/Common/emacs/personal")
                      (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/personal/custom.el")))
    ("prelude" . ((user-emacs-directory . "~/Workspace/Public/dotfiles/.emacs.prelude")
                     (custom-file . "~/Workspace/Public/dotfiles/Common/emacs/prelude/custom.el")
                     (env . (("PRELUDE_PERSONAL_DIR" . "~/Workspace/Public/dotfiles/Common/emacs/prelude")))))
    )
