# Do not insert a blank line between shell prompts
add_newline = false

# Set the format string
format = """
$git_branch\
$git_state\
$git_status\
$directory\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[✗](red)"
vicmd_symbol = "[❮](green)"

[directory]
style = "green"

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
style = "green"

[git_status]
stashed = "≡"
up_to_date = "✓"
style = "cyan"

[git_state]
style = "cyan"
