# Do not insert a blank line between shell prompts
add_newline = false

format = """
[┌─| ](bold green)$all\
[└─](bold green)$character"""

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[✗](bold red)"
