# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Do not insert a blank line between shell prompts
add_newline = false

# Set the format string
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[✗](red)"
vicmd_symbol = "[❮](green)"

[directory]
truncation_length = 1
style = "green"

[git_branch]
# format = "[$branch(:$remote_branch)]($style) "
style = "green"

[git_status]
stashed = "≡"
style = "cyan"

[git_state]
style = "cyan"
