# Do not insert a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "λ"
[character]
success_symbol = "[λ](bold green)"

# Do not disable the package module, hiding it from the prompt completely
[package]
disabled = false
