live_config_reload = true
working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#f2f2f2"
red = "#d00000"
green = "#008900"
yellow = "#808000"
blue = "#0000ff"
magenta = "#dd22dd"
cyan = "#008899"
white = "#595959"

[colors.normal]
black = "#ffffff"
red = "#a60000"
green = "#006800"
yellow = "#6f5500"
blue = "#0031a9"
magenta = "#721045"
cyan = "#005e8b"
white = "#000000"

[colors.primary]
background = "#ffffff"
foreground = "#000000"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "None"

[env]
TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 2

[shell]
args = ["-l", "-c", "tmux attach || tmux new -s Default"]
program = "/usr/bin/bash"

[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 140
lines = 30

[window.padding]
x = 1
y = 1
