live_config_reload = true
working_directory = "None"

# colors
import = ["~/.config/alacritty/alacrity-modus-operandi.toml"]

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "None"

[env]
TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 2

[shell]
# args = ["-l", "-c", "tmux attach || tmux new -s Default"]
program = "/usr/bin/bash"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 140
lines = 30

[window.padding]
x = 1
y = 1
