#!/usr/bin/env bash

# Exports
export ALTERNATE_EDITOR=""
export VISUAL="emacsclient -c -n -a ''" # $VISUAL opens in GUI with non-daemon as alternate
export EDITOR="emacsclient -t -a ''"    # $EDITOR should open in terminal
export TERM=xterm-256color

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# ssh
alias ssh="TERM=xterm-256color ssh"
export SSH_KEY_PATH="$HOME/.ssh/dsa_id"

# emacs
if type emacs >/dev/null 2>/dev/null; then
    alias em="emacsclient -c -n -a ''"     # opens the GUI
    alias emt="emacsclient -t -a ''"       # used to be "emacs -nw"
    alias semt="sudo emacsclient -t -a ''" # used to be "sudo emacs -nw"

    ediff() { emacsclient -t -a '' --eval "(ediff-files \"$1\" \"$2\")"; }
    edired() { emacsclient -t -a '' --eval "(progn (dired \"$1\"))"; }
    ekill() { emacsclient --eval '(kill-emacs)'; }
fi

# bash keybidings (man readline)
bind '"\C-\b": backward-kill-word' # make C-Backspace act as in emacs

# utils
alias ls='ls --color'
alias ll='ls -AlFh --color'
alias cp="cp -iv"
alias mv="mv -iv"
alias tree="tree --dirsfirst -a -I 'node_modules|.git'"
alias ag='ag --hidden --ignore node_modules --ignore .git'

# atool to extract archives
if type atool >/dev/null 2>/dev/null; then
    unpack() {
        atool --extract --explain "$@"
    }
fi

# exa
if type exa >/dev/null 2>/dev/null; then
    alias ls='exa --group-directories-first --color=auto'
    alias ll='exa -agFlh --group-directories-first --color=auto'
fi

# ripgrep
if type rg >/dev/null 2>/dev/null; then
    alias grep='rg -S --color=auto'
fi

# bat
if type bat >/dev/null 2>/dev/null; then
    alias bat='bat --theme ansi'
    # alias cat='bat --theme ansi'
fi

# gpg is not gpg2 if installed
if type gpg2 >/dev/null 2>/dev/null; then
    alias gpg='gpg2'
fi

# vim
if type nvim >/dev/null 2>&1; then
    alias vim='nvim'
fi
alias vi=vim

# surf: these options are very opinionated, disabling images, javascript, etc.
if type surf >/dev/null 2>&1; then
    alias surf="surf -giKMnps"
fi

#
# Mac Stuff
#
if [ "$(uname -s)" = "Darwin" ]; then
    # Toggle hidden files on mac
    alias show_hidden_files='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
    alias hide_hidden_files='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

    # Enable font smoothing
    defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

    # Symlink workspace volume
    if [ ! -d "$HOME/Workspace" ]; then
        ln -nfs /Volumes/Workspace/ ~/Workspace
    fi
fi

#
# Linux Stuff
#
if [ "$(uname -s)" = 'Linux' ]; then
    alias open='xdg-open'
    alias alacritty='env WINIT_UNIX_BACKEND=x11 alacritty'

    # Known bug with gpg on Fedora
    gpg_pcscd_restart() {
        sudo systemctl restart pcscd
    }
fi

#
# Emacs vterm (https://github.com/akermu/emacs-libvterm)
#
if [ "$INSIDE_EMACS" = 'vterm' ] &&
    [ -n "$EMACS_VTERM_PATH" ] &&
    [ -f "$EMACS_VTERM_PATH/etc/emacs-vterm-bash.sh" ]; then
    . "$EMACS_VTERM_PATH/etc/emacs-vterm-bash.sh"
fi

#
# Fuzzy Finder (https://github.com/lotabout/skim)
#
. "${HOME}/.config/shell/skim"
